### ISSUE TITLE
Completed list indicator

### ISSUE THREAD

**Issue by flogaribal** [EdsonBueno/infinite_scroll_pagination#1]
Thanks for this awesome plugin! It works like a charm for purposes like you explained in doc.
However I did find a way to stop displaying the `newPageProgressIndicator` once the whole list has been loaded.

I think I have to notify the `dataSource` that the list is completed but I cannot find a way to do this...
Could you explain to me how to do this please?

**Comment by EdsonBueno** [comment]
Hi @flogaribal, thank you so much!
Simply set your next page key no `null`. To do that, simply pass `null` to the second parameter of `notifyNewPage`.
In the [cookbook](https://pub.dev/packages/infinite_scroll_pagination/example#simple-usage), you can notice that `nextPageKey` is actually null if we've loaded all items.
