### ISSUE TITLE
[Question]How to obtain the ListView's offset....

### ISSUE THREAD

**Issue by SeasonLeee** [EdsonBueno/infinite_scroll_pagination#100]
As stated in the title... it seem we are not able to get this value from the controller....

Any thoughts?

Thanks...

**Comment by EdsonBueno** [comment]
The same way you would do it with a regular `ListView`.
[Here](https://stackoverflow.com/questions/43881103/current-scroll-offset-inside-a-flutter-listview-sliverlist-etc) are some alternatives.
