### ISSUE TITLE
RefreshIndicator disappear before new list arrive

### ISSUE THREAD

**Issue by DZESU** [EdsonBueno/infinite_scroll_pagination#103]
As the title suggest, Is there a way to make RefreshIndicator still showing until the new data arrive?

**Comment by EdsonBueno** [comment]
Hi @DZESU .
One of the ways I can think of is using a [Completer](https://api.dart.dev/stable/2.12.4/dart-async/Completer-class.html).
So, you provide your `_completer.future` to the `onRefresh` property of your `RefreshIndicator`, and once the new page arrives, simply trigger that completer.

I'm closing the issue but feel free to continue the discussion and ping me if you need any help.

**Comment by DZESU** [comment]
I see, Thank you for your help. This library helps solves a lot of my problems. 👍

**Comment by EdsonBueno** [comment]
I already posted the solution to your problem @changlan .
Have you tried using `AutomaticKeepAliveClientMixin`?
