### ISSUE TITLE
Delay load the paging controller

### ISSUE THREAD

**Issue by dalton5** [EdsonBueno/infinite_scroll_pagination#107]
Hi,

I use a map and based on the position I have I launch my search.

Then I can't use the addPageRequestListener in the oninit.

So to do it, I created a method named setup listener:

      `setupListener() {
          _pagingController.addPageRequestListener((pageKey) async {
            await updateSource(pageKey);
          });
      
        }`

The setup listener is called when the onmapinitialized is raised and I got the position.

But when I do this the pagingcontroller is not raised and refreshed.

So I plan to do:  _pagingController.notifyPageRequestListeners(0);

in my setup listeners./

Is it a good way to do it?

**Comment by EdsonBueno** [comment]
Hi @dalton5 ,
It would be better if you wait until you have your position to add the `PagedListView` to the screen.
Thanks
