### ISSUE TITLE
Plugin stopped Working 

### ISSUE THREAD

**Issue by abdulec90** [EdsonBueno/infinite_scroll_pagination#109]
This plugin was working fine until yesterday.
Suddenly it stopped working and displaying an error screen without specifying the cause of it.
Please look into it urgently.
It says something went wrong.
![Screenshot_1624374134](https://user-images.githubusercontent.com/28142824/123043156-85418f00-d415-11eb-9318-3a3aa52468a8.png)

**Comment by DZESU** [comment]
May your API return something from that crash your code. As far as I know, This view happened when `PagingController.error` is assigned, I could be wrong tho.

**Comment by abdulec90** [comment]
@DZESU  Thank you for your response . let me debug PagingController.error to check for exact error

**Comment by abdulec90** [comment]
@DZESU  found the issue, it was related to flutter null safety, as i was assigning null to a variable.
now it is working fine.

**Comment by EdsonBueno** [comment]
Thank you for your help @DZESU
