### ISSUE TITLE
How to use with GetX

### ISSUE THREAD

**Issue by emman-ok** [EdsonBueno/infinite_scroll_pagination#110]
Looking for the documentations on how to use with Getx State management.

**Comment by EdsonBueno** [comment]
Hi @emman-ok .
I can work on that. I'm just not sure when I'll have the time for it, so I'll leave this issue open in case someone wants to raise a PR for it.

**Comment by Rexios80** [comment]
I just put my PagingController in a GetxController. Is there a reason that couldn't work for you?

**Comment by FarhanSajid1** [comment]
@Rexios80 it seems if you it to a getxcontroller, and you go to another page that uses a paging controller it doesn't get reset?

**Comment by Rexios80** [comment]
@FarhanSajid1 Are you sharing the PagingController between the two pages? Also are you actually navigating between pages or switching out data on the same page?

I'm not sure what your exact issue is based on what you said. You might have to give more detail.

**Comment by FarhanSajid1** [comment]
@Rexios80 apologies for the lack of information.

So I have a Get.to() logic within widgets on a list screen. On the first iteration everything works as expected, but if I click back and click on another widget that has a Get.To() back to the same screen it appears as if the pagingController does not get recreated.

I have a work around for this, and that is to do a refresh of the pagingController when the screen is created.

In my widget I have this logic on the tap
```
    InkWell(
        onTap: () {
          playerProfileController.player
              .value = "hello"!;
          Get.to(
              () =>
                  const PlayerProfileScreen(),
              preventDuplicates: false);
        },
```

Now we navigate to the `PlayerProfileScreen`, there we do a find
```
class _PlayerProfileScreenState extends State<PlayerProfileScreen> {
  // find the PlayerProfileController that has been initiated
  PlayerProfileController playerProfileController = Get.find();
```

The controller has a pagingController
```
class PlayerProfileController extends GetxController {
  PagingController<String, OneVsOneListMatchWidget> pagingController =
      PagingController(firstPageKey: "");
....
  @override
  void onInit() async {
    resetPagingController();
    super.onInit();
  }

  // resetPagingController resets the paging controller
  void resetPagingController() {
    pagingController = PagingController(firstPageKey: "");
    pagingController.addPageRequestListener((pageKey) async {
      if (kDebugMode) {
        print('calling paging controller again!');
      }
      if ((pagingController.value.status == PagingStatus.loadingFirstPage ||
              pagingController.value.status == PagingStatus.ongoing) &&
          isLoadingStarted) return;
      isLoadingStarted = true;
      getPlayerTimeline(pageKey);
      isLoadingStarted = false;
    });
  }
```

Now this logic as is results in the following:
If I click on the widget (the first block of code), I do get redirected to the Profile Screen every thing there gets rebuild correctly except for the pagingController, it appears to have the data from the last time we visit the screen.


The workaround that I've seen is to call the `resetPagingController` function above on the actual screen.
```
  PlayerProfileController playerProfileController = Get.find();

  @override
  void initState() {
    super.initState();
    // the pagination controller MUST be refreshed to prevent stale data from being server
    playerProfileController.resetPagingController();
  }

```
Not sure if that makes sense, I'm probably using GetX + infinite paging incorrectly, but this is what I have at the moment.

**Comment by FarhanSajid1** [comment]
@Rexios80 I am switching pages, creating a new controller and I am supposed to get new data. 

Now I am noticing when I click back, sometimes the data is replaced with the next screen's data.

**Comment by pieroashady** [comment]
Nevermind, i found it..

`static const _pageSize = 10;
  final PagingController<int, JobPostData> pagingController =
      PagingController(firstPageKey: 0);
      
      _fetchPage(int pageKey) async {
    try {
      await getJobs(queryParameters: {r"$limit": _pageSize, r"$skip": pageKey});
      final isLastPage = jobs.value.data!.length < _pageSize;
      if (isLastPage) {
        pagingController.appendLastPage(jobs.value.data!);
      } else {
        final nextPageKey = pageKey + jobs.value.data!.length;
        pagingController.appendPage(jobs.value.data!, nextPageKey);
      }
    } catch (error) {
      pagingController.error = error;
    }
  }`
  
  hope this helps others

**Comment by blackkara** [comment]
> Nevermind, i found it..
> 
> * first, add this variable on your controller
> 
> ```
> static const _pageSize = 10;
> final PagingController<int, JobPostData> pagingController =
>       PagingController(firstPageKey: 0);
> ```
> 
> * then, initialize the paging controller on your controller initstate
> 
> ```
> @override
> void onInit() {
>   super.onInit();
>   pagingController.addPageRequestListener((pageKey) {
>     _fetchPage(pageKey);
>   });
> }
> ```
> 
> * then the method itself
> 
> ```
> _fetchPage(int pageKey) async {
>  try {
>    await getJobs(queryParameters: {r"$limit": _pageSize, r"$skip": pageKey});
>    final isLastPage = jobs.value.data!.length < _pageSize;
>    if (isLastPage) {
>      pagingController.appendLastPage(jobs.value.data!);
>     } else {
>        final nextPageKey = pageKey + jobs.value.data!.length;
>        pagingController.appendPage(jobs.value.data!, nextPageKey);
>     }
>  } catch (error) {
>    pagingController.error = error;
>  }
> }
> ```
> 
> * finally the widget
> 
> ```
> PagedListView<int, JobPostData>(
>    pagingController: _homeController.pagingController,
>    padding: EdgeInsets.only(
>      top: 8,
>      bottom: MediaQuery.of(context).size.height * 0.17,
>    ),
>    builderDelegate: PagedChildBuilderDelegate<JobPostData>(
>     itemBuilder: (context, item, index) {
>        return Jobs(
>          jobData: item,
>        );
>      },
>    ),
> );
> ```
> 
> hope this helps others

But what about disposing the `pagingController` ? 

I tried disposing it in `onClose` of controller, but gives me a "pagingcontroller was used after being disposed." if I leave the page while fetching data in progress.

**Comment by fbanyai** [comment]
As we usually use `StatelessWidget` in GetX I noticed that the `pagingController.PageRequestListener` was not being triggered for some reason (or maybe we could say, it wasn't being *started*)

The solution was to force triggering this listener at the begining of the page lifecyle by simply adding in the page controller:

```dart
@override
void onReady() {
  pagingController.notifyPageRequestListeners(1); // My first page index is 1

  super.onReady();
}
```

If needed be the complete source code is:

```dart
class StoresController extends GetxController {
  final ApiService api = Get.find();

  final pagingController = PagingController<int, Store>(firstPageKey: 1);

  String? keyword;

  @override
  void onInit() async {
    pagingController.addPageRequestListener((pageKey) => _fetchPage(pageKey));

    super.onInit();
  }

  @override
  void onReady() {
    pagingController.notifyPageRequestListeners(1);

    super.onReady();
  }

  @override
  void onClose() {
    pagingController.dispose();

    super.onClose();
  }

  _fetchPage(pageKey) async {
    try {
      final data = await api.stores(keyword, pageKey, kDefaultPageSize);

      final isLastPage = data.length < kDefaultPageSize;

      if (isLastPage) {
        pagingController.appendLastPage(data);
      } else {
        final nextPageKey = ++pageKey; // pageKey is index based (not offset based as in the documentation of the package)

        pagingController.appendPage(data, nextPageKey);
      }
    } catch (error) {
      pagingController.error = error;
    }
  }
 
  submit() async {
    if (formKey.currentState!.isValid == false) return;

    if (formKey.currentState != null) {
      keyword = formKey.currentState!.fields['keyword']?.value;
    }

    pagingController.refresh();
  }
}
```
