### ISSUE TITLE
[Feature Request] make AppendedSliverChildBuilderDelegate public

### ISSUE THREAD

**Issue by clragon** [EdsonBueno/infinite_scroll_pagination#114]
I'm currently trying to create a custom layout with `PagedSliverBuilder` and `StaggeredGridView.custom`.

In doing so, it would actually help if `AppendedSliverChildBuilderDelegate` was public, since otherwise I would have to write my own custom delegate which the exact same functionality.

Could you add an export?

**Comment by EdsonBueno** [comment]
Hi @clragon.
How about you fork the repository and raise a PR for a `PagedStaggeredGridView` instead?
Thank you

**Comment by clragon** [comment]
Hi @EdsonBueno,

sure. I copied the code and I am using the duplicated file. here's what it looks like
```dart
Widget gridBuilder(
  BuildContext context,
  IndexedWidgetBuilder itemBuilder,
  int itemCount,
  WidgetBuilder? appendixBuilder,
) {
  return SliverStaggeredGrid(
    gridDelegate: SliverStaggeredGridDelegateWithFixedCrossAxisCount(
      staggeredTileBuilder: tileBuilder,
      crossAxisCount: crossAxisCount,
    ),
    delegate: AppendedSliverChildBuilderDelegate(
      childCount: itemCount,
      builder: itemBuilder,
      appendixBuilder: appendixBuilder,
    ),
  );
}
```
which is the function I pass to the `PagedSliverBuilder` with 
```dart
completedListingBuilder: gridBuilder,
loadingListingBuilder: gridBuilder,
errorListingBuilder: gridBuilder,
```

it would be very useful if `AppendedSliverChildBuilderDelegate` public.

**Comment by clragon** [comment]
though since you mentioned it, 
writing a PR for `PagedStaggeredGridView` is not a bad idea, 
I think I might pursue that.
