### ISSUE TITLE
[Feature request] refresh with data replacement

### ISSUE THREAD

**Issue by clragon** [EdsonBueno/infinite_scroll_pagination#115]
When using a `SmartRefresher` and calling `pagingController.refresh()` inside the `onRefresh` method, 
this will lead to the `pagingController` throwing all items away and then loading new ones. 

This also means, that during the loading, the initial loading screen of the Page is shown. 
The `SmartRefresher` header is also shown. This means, there are now two loading indicators on the screen.

What I would wish as a feature is refreshing with data replacement.
This would mean:
- calling refresh with an optional parameter boolean that defaults to false (e.g. `refresh(seamless: true)`)
- pagingController loading new data, but not emptying the items just yet
- when the data is loaded successfully, the items are _replaced_. 
- if the loading fails, items arent touched

**Comment by EdsonBueno** [comment]
Hi @clragon .
I'm not sure what `SmartRefresher` is, but I'm guessing it's not from Flutter.
You can do what you want simply by not calling `pagingController.refresh()`.
Inside your `onRefresh`, call a function you create that will load the first page again and does exactly what you want (e.g. not replacing item if it fails).
If you want to keep the indicator on the screen until items are loaded, you can use [this solution](https://github.com/EdsonBueno/infinite_scroll_pagination/issues/103).

**Comment by clragon** [comment]
Hi @EdsonBueno,

this seems to lead to a weird behaviour where the `pagingController` immediately requests the second page as well,
without the user actually scrolling there.
Code:
```dart
    try {
      List<Post> posts =
          await client.posts(tags, pagingController.firstPageKey);
      pagingController.value = PagingState(
        nextPageKey: pagingController.firstPageKey + 1,
        error: null,
        itemList: posts,
      );
      refreshController.refreshCompleted();
    } on DioError catch (error) {
      pagingController.error = error;
      refreshController.refreshFailed();
    }
```

**Comment by fullflash** [comment]
pagingController.refresh() resets previously loaded content. 

authors requested feature "pagingController loading new data, but not emptying the items just yet" is very useful.

**Comment by sou1maker** [comment]
@clragon Extends and override these methods to get what you want
```dart

class PagingControllerExtent<PageKeyType, ItemType>
    extends PagingController<PageKeyType, ItemType> {
  PagingControllerExtent({
    required super.firstPageKey,
    super.invisibleItemsThreshold,
  });

  /// Whether it is in the state of background refresh
  bool background = false;

  @override
  void refresh({bool background = false}) {
    if (background) {
      this.background = true;
      // Since the state of PagingState has too much influence,
      // skip it here and directly notifyPageRequestListeners.
      notifyPageRequestListeners(firstPageKey);
    } else {
      super.refresh();
    }
  }

  @override
  void appendPage(List<ItemType> newItems, PageKeyType? nextPageKey) {
    // Add judgment here
    final previousItems = background ? <ItemType>[] : value.itemList ?? <ItemType>[];
    final itemList = previousItems + newItems;
    value = PagingState<PageKeyType, ItemType>(
      itemList: itemList,
      error: null,
      nextPageKey: nextPageKey,
    );
    // reduction
    background = false;
  }
}

```

**Comment by Heilum** [comment]
good, I think the default value of 'background' parameter of 'refresh' method better be  true!

**Comment by elliotkhd** [comment]
The solution is so good until version 5.0.0 released, now it's not working for the latest version, any update?
