### ISSUE TITLE
Set firstPageKey to be empty or null in PagingController.

### ISSUE THREAD

**Issue by eldrigo** [EdsonBueno/infinite_scroll_pagination#116]
I want the firstPageKey param in PagingController to be empty or null, is there a way i can do that ?

**Comment by EdsonBueno** [comment]
Hi @eldrigo. Thank you for opening this issue.
Yes, you shouldn't have any problem with that. Did you find a problem doing that?
I'm closing the issue for now, but feel free to continue the discussion.

**Comment by eldrigo** [comment]
My bad, it worked by changing the page key type to dynamic.
