### ISSUE TITLE
How to add flutter_staggered_grid_view as itembuilder type?

### ISSUE THREAD

**Issue by oneoffice** [EdsonBueno/infinite_scroll_pagination#117]
Hi, is there any way to implement staggeredGridView, i use childAspectRatio but it's working  not correct?

**Comment by EdsonBueno** [comment]
Hi @oneoffice.
I'm working on a `PagedStaggeredGridView`, should be out by this weekend.

**Comment by sangeren** [comment]
Hi @EdsonBueno 
How can i use PagedStaggeredGridView?

**Comment by oneoffice** [comment]
> Hi @oneoffice.
> I'm working on a `PagedStaggeredGridView`, should be out by this weekend.

anything update for this?

**Comment by malikdoksoz** [comment]
any update?

**Comment by 0wzZZzz6** [comment]
up

**Comment by 0wzZZzz6** [comment]
`  infinite_scroll_pagination:
    git:
      url: https://github.com/EdsonBueno/infinite_scroll_pagination.git
      ref: develop`
      
  I import it like this where the `PagedStaggeredSliverGrid` is on.

**Comment by KamisatoNobitta** [comment]
> Hi [@oneoffice](https://github.com/oneoffice). I'm working on a `PagedStaggeredGridView`, should be out by this weekend.

anything update for this now?
It seems that there is currently no `dev` branch or `PagedStaggeredSliverGrid`.
