### ISSUE TITLE
Center Try again widget

### ISSUE THREAD

**Issue by chitgoks** [EdsonBueno/infinite_scroll_pagination#121]
![Screenshot_20210718_232355_org droidgox katunog](https://user-images.githubusercontent.com/3955470/126072842-3b14c720-c00c-411e-bc6a-be540b6bd520.jpg)

perhaps an option to set this at vertical center?

**Comment by EdsonBueno** [comment]
Hey @chitgoks .
Try playing with the `shrinkWrapFirstPageIndicators` property of your `PagedListView`.
Thanks.

**Comment by chitgoks** [comment]
hi @EdsonBueno shrinkWrapFirstPageIndicators  is only true or false and nothing changed regardless. Perhaps you mean  firstPageErrorIndicatorBuilder? I wish to use the same widget as the one above which is the default the library uses. I only wish to have this centered vertically.

**Comment by chitgoks** [comment]
The issue here is FirstPageExceptionIndicator . Column should have mainAxisAlignment: MainAxisAlignment.center so it will be vertically aligned at the center.

Can a feature request be possible, such that to add a property to have this center aligned vertically? does not look good if it is at the top.

**Comment by EdsonBueno** [comment]
Hey @chitgoks .
In that case I recommend you to replace the default indicator with one of your own using the `firstPageErrorIndicatorBuilder`.

**Comment by chitgoks** [comment]
your default is pretty much ok. its jsut the vertical alignment thats the issue. ill just copy your dart file then if you dont plan to add an option.
