### ISSUE TITLE
Add option to delay first page request until explicitly asked using the controller

### ISSUE THREAD

**Issue by TomasWeg** [EdsonBueno/infinite_scroll_pagination#124]
Add an option, for example, on the `PagedListView` which adds the ability to "wait" until a method is called then the first page is requested.
```dart
PagedListView<String, dynamic>(
   pagingController: pagingController,
   delayFirstPage: true,
   builderDelegate: PagedChildBuilderDelegate(
       itemBuilder: (context, item, index) => Container(),
  ),
),
```
Then, using the PagingController, we can use:
```dart
pagingController.requestFirstPage();
```

Why is this useful?
In search bars for example, we don't want the CircularProgressIndicator to appear unless the user starts writing something in the TextField

**Comment by NamanShergill** [comment]
You could just use Visibility() to hide the widget until something is searched in the search bar.

**Comment by EdsonBueno** [comment]
Hi @TomasWeg ,
In that case you'd be better off not inserting your `PagedListView` in the widget tree until you actually want to show something. An alternative would be @NamanShergill 's suggestion.

Thank you so much!
