### ISSUE TITLE
[Question] How to use with Firestore

### ISSUE THREAD

**Issue by Nader2004** [EdsonBueno/infinite_scroll_pagination#125]
Hello  thanks for this amazing package. 

I do have a question, how to use this package with firestore. How to implement for example the pageKey in a firestore query. Can anyone please help with a sample. That will be highly appreciable!

Thanks!

**Comment by Nader2004** [comment]
So after some experementing , I should just get the last `DocumentSnapshot` of the current List and pass it in the `.startAfterDocument()` Query.

**Comment by UsamaKarim** [comment]
@Nader2004

Hi, 

How did you use `DocumentSnapshot`as the pageKey?

**Comment by UsamaKarim** [comment]
Found the solution. `PagingController` requires `PageKeyType`. So using it like `PagingController<DoucmentSnapshot<T>, <T>` while initializing can easily solve the problem. For `T` provide your class type which is usually a model a class

**Comment by franzenitlab** [comment]
@UsamaKarim when using this package, how did you specified which was your firstPageKey, using Firestore? How did you initialized the value/obtained the first cursor?

**Comment by UsamaKarim** [comment]
> @UsamaKarim when using this package, how did you specified which was your firstPageKey, using Firestore? How did you initialized the value/obtained the first cursor?

I am storing `lastDocument` from the firestore & it is null at first.
`DocumentSnapshot<Product>? _lastDocument;`

```dart
  static const _pageSize = 6;

  late final PagingController<DocumentSnapshot<Product>?, Product>
      _pagingController;

  Future<void> _fetchPage(DocumentSnapshot<Product>? lastDocument) async {
    try {
      // final newItems = await RemoteApi.getCharacterList(pageKey, _pageSize);
      final snapshot =
          await sl.get<ShopViewModel>().getAllProducts(lastDocument);
      final isLastPage = snapshot.docs.length < _pageSize;
      final productList = snapshot.docs.map((e) => e.data()).toList();
      if (isLastPage) {
        _pagingController.appendLastPage(productList);
      } else {
        _lastDocument = snapshot.docs.last;
        _pagingController.appendPage(productList, _lastDocument);
      }
    } catch (error) {
      _pagingController.error = error;
    }
  }
```
