### ISSUE TITLE
Is it possible to implement reorderable/drag and drop list elements using the package?

### ISSUE THREAD

**Issue by NamanShergill** [EdsonBueno/infinite_scroll_pagination#135]

**Comment by EdsonBueno** [comment]
Hi @NamanShergill,
It should be! Worst case scenario, if you can't use `PagedListView`, you can just use the underlying `PagedSliverBuilder` to build your own layout.
Thank you.

**Comment by NamanShergill** [comment]
> Hi @NamanShergill,
> It should be! Worst case scenario, if you can't use `PagedListView`, you can just use the underlying `PagedSliverBuilder` to build your own layout.
> Thank you.

Thank you for the response!

I suppose there's no straightforward way to integrate this package with this [specific widget](https://pub.dev/packages/reorderables#reorderablesliverlist)?

Seems like one would need to write a similar compatible implementation on their own, please correct me if I'm wrong.

@EdsonBueno

**Comment by NamanShergill** [comment]
> At a glance it seems doable to me.
> I recommend you take a look at how the [PagedSliverList](https://github.com/EdsonBueno/infinite_scroll_pagination/blob/master/lib/src/ui/paged_sliver_list.dart) code works. Then you can try writing an adaptation of your own that uses the `ReorderableSliverList` instead. You'll also need to create another version of [this](https://github.com/EdsonBueno/infinite_scroll_pagination/blob/master/lib/src/utils/appended_sliver_child_builder_delegate.dart) that uses the ReorderableSliverChildBuilderDelegate instead.
> Let me know how your research goes.

I'll give it a shot. Thank you for the advice, it's very helpful!
