### ISSUE TITLE
[Feature Request] Keep only a subset of items.

### ISSUE THREAD

**Issue by PaulRudin** [EdsonBueno/infinite_scroll_pagination#138]
At the moment (if I understand correctly) the PagingController keeps hold of all the items passed to appendLastPage. But in the case where there are very many pages, this could mean that we have very many items in memory. It would be nice to be able to drop some and re-request if necessary. This would fit well with https://github.com/EdsonBueno/infinite_scroll_pagination/issues/56 in order to re-request earlier pages.

**Comment by EdsonBueno** [comment]
Hey @PaulRudin ,
What's kept in memory is just the model objects, not the widgets; those are managed by Flutter itself.
Doing what you're asking for would completely change the API and make it much less intuitive for the lay user.
Thank you for your suggestion!
