### ISSUE TITLE
Infinite Scroll PagingController not calling inside function

### ISSUE THREAD

**Issue by rvn9** [EdsonBueno/infinite_scroll_pagination#146]
When user click the button, loadComment should be running. but inside pagingcontroller the cubit is not being called.
I tried to make instagram comments, top comment (ininifty list), replies (infinity list).

```dart
  loadComment() {
    _pagingControllerReplies.addPageRequestListener(
      (pageKey) {
        tempPageKey = pageKey;
        context.read<CommentCubit>().loadReplies(
              BlocProvider.of<PostItemCubit>(context).postItems.id,
              widget._commentData.id,
              0,
            );
      },
    );

    _pagingControllerReplies.addStatusListener((status) {
      debugPrint(status.toString());
      if (status == PagingStatus.subsequentPageError) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text(
              'Something went wrong while fetching a new page.',
            ),
            action: SnackBarAction(
              label: 'Retry',
              onPressed: () =>
                  _pagingControllerReplies.retryLastFailedRequest(),
            ),
          ),
        );
      }
    });
  }
```

**Comment by EdsonBueno** [comment]
Hey @rvn9 .
I don't think you understand how the package works.
Calling `addPageRequestListener` doesn't force the API to be called. You just set up a listener to be called **when** a page is needed.
I recommend you follow [this tutorial](https://www.raywenderlich.com/14214369-infinite-scrolling-pagination-in-flutter) to understand a bit more how the package works.

I'm closing the issue now, but feel free to continue the discussion.
