### ISSUE TITLE
how to use with ReorderableListView

### ISSUE THREAD

**Issue by Nader2004** [EdsonBueno/infinite_scroll_pagination#147]
Hello . I wish i can use this package with ReorderableListView. Sometimes i might want to list items to be ordered on incoming stream events. If there is an another way of achieving this, it will be appriciatable.

**Comment by EdsonBueno** [comment]
Hey @Nader2004 
Have you taken a look [at this](https://pub.dev/packages/infinite_scroll_pagination/example#custom-layout)?
