### ISSUE TITLE
poping the screen before the page loads crash the app on ios

### ISSUE THREAD

**Issue by papogy** [EdsonBueno/infinite_scroll_pagination#15]
hello everyone , i get this warning when i am trying to pop the screen ( i click on the back to the previous page button  ) before the page loads ( the data comes from the server ) .

- on android i get only this warning .  
- on ios i get the same warning and the app crashes.

![image](https://user-images.githubusercontent.com/35198750/98225080-9015e500-1f54-11eb-8c43-1908e5ce2966.png)

any help please ?

**Comment by EdsonBueno** [comment]
Hi @papogy.
The error message tells you what the problem is and what you can do to fix it.
Your `Future` completed after you disposed your widget (and consequently your `PagingController`).

A quick fix is surrounding your calls to `appendPage`, `appendLastPage` and `error` with:
```dart
if (mounted) {
   // EXAMPLE:  _pagingController.appendLastPage(...)
}
```

**Comment by papogy** [comment]
@EdsonBueno this is already done , all the appendPage, appendLastPage calls are surounded by the " if (mounted) " condition .
apparentlly mounted = true when i click on the back button . and then the error remains

**Comment by EdsonBueno** [comment]
@papogy Try [this](https://github.com/EdsonBueno/infinite_scroll_pagination/pull/7#issuecomment-712956309) solution!

**Comment by papogy** [comment]
@EdsonBueno thanks for your response , that helped !
