### ISSUE TITLE
Can I use Infinite Scroll Pagination for DataTable?

### ISSUE THREAD

**Issue by paakjis** [EdsonBueno/infinite_scroll_pagination#150]
Hi. 

My app is build with DataTable, is it possible to use Infinite Scroll Pagination ?
I don't see any possible way to do this, but maybe someone here will know.

Thanks.

**Comment by clragon** [comment]
yes, you can use a `PagedSliverBuilder` to make your own implementation.

**Comment by rajada1** [comment]
> yes, you can use a `PagedSliverBuilder` to make your own implementation.

Do you have an example of how to do this?
