### ISSUE TITLE
Unhandled Exception: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).

### ISSUE THREAD

**Issue by krishna700** [EdsonBueno/infinite_scroll_pagination#151]
**[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
E/flutter (14783): Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.**

` Future<void> _fetchPage(int pageKey) async {
    WidgetsBinding.instance?.addPostFrameCallback(
      (timeStamp) async {
        try {
          final newPage = await OrderHistoryRepository().all(
            page: pageKey,
          );

          if (newPage.data != null && newPage.data!.length == 0) {
            isEmptyOrderList = true;
          }

          final previouslyFetchedItemsCount =
              _pagingController!.itemList?.length ?? 0;

          final isLastPage = newPage.isLastPage(
            previouslyFetchedItemsCount,
          );
          final newItems = newPage.data;
          if (isLastPage) {
            _pagingController!.appendLastPage(
              newItems!,
            );
          } else {
            final nextPageKey = pageKey + 1;
            _pagingController!.appendPage(
              newItems!,
              nextPageKey,
            );
          }
        } catch (error, s) {
          _pagingController!.error = error;
          debugPrint(
            error.toString(),
          );
          debugPrint(
            s.toString(),
          );
        }
        // finally {
        //   setState(() {});
        // }
      },
    );
  }`

  
Can someone help why I am getting this error, not able to find anything from stack trace. 
  Thanks

**Comment by clragon** [comment]
you are probably calling setstate after this widget was already disposed.
Just like the error message says, you can check `mounted` before calling setstate to avoid this error.

**Comment by EdsonBueno** [comment]
@krishna700 what @clragon said is correct! Please, try doing that and let us know the result!
I'm closing the issue for now, but feel free to continue the discussion! Thanks!
