### ISSUE TITLE
Scroll to the start of list

### ISSUE THREAD

**Issue by FedrBodr** [EdsonBueno/infinite_scroll_pagination#162]
Hello everyone, I can't find a way to scroll up programmatically. For example, in a SingleChildScrollView, the controller can call _scrollViewController. animateTo(_scrollViewController. position. minScrollExtent). 
I can’t find anything similar for PagedListView and PagingController, tell me if there is similar functionality in this component and where to dig?

**Comment by clragon** [comment]
PagingController is for data.
All Scrollable Views have a ScrollController.

You can pass a ScrollController to the PagedListView and control it that way.

**Comment by FedrBodr** [comment]
Omg! ) Really they still exist) Thank you so much, I just was blind
