### ISSUE TITLE
No internationalization possible

### ISSUE THREAD

**Issue by clemsciences** [EdsonBueno/infinite_scroll_pagination#167]
Your package is great but it contains text that is in English. The developper cannot change is through parameters.

**Comment by clragon** [comment]
You can display your own widgets for loading and errors which can contain translations.

**Comment by andr3i4o** [comment]
Yes, but the custom widget that extends FirstPageExceptionIndicator for example can receive a title, message and onTryAgain, but the onTryAgain button has a static text "Try Again" in English. It would be great to have another parameter like OnTryAgainText with a default value.

**Comment by heshesh2010** [comment]
up
