### ISSUE TITLE
remove item

### ISSUE THREAD

**Issue by mbfakourii** [EdsonBueno/infinite_scroll_pagination#17]
Hello, how do we delete an item after clicking the method?

**Comment by EdsonBueno** [comment]
**Option 1**
```dart
final newList = List.of(_pagingController.itemList);
newList.removeWhere(...);
_pagingController.itemList = newList;
```

**Option 2**
```dart
_pagingController.itemList.removeWhere(...);
_pagingController.notifyListeners();
```

In short, either you modify a copy of the old list, or you call notifyListeners by yourself.

**Comment by subzero911** [comment]
@EdsonBueno currently, direct notifyListeners() call is considered to be an error

![image](https://user-images.githubusercontent.com/12999702/123650811-99312a80-d833-11eb-9b75-30e4ae8414f8.png)

`The member 'notifyListeners' can only be used within 'package:flutter/src/foundation/change_notifier.dart' or a test.dart(invalid_use_of_visible_for_testing_member)`

I noticed you added two methods: `notifyStatusListeners` and `notifyPageRequestListeners`. Should we use one of them instead?

**Comment by EdsonBueno** [comment]
Hi @subzero911. Thank you for notifying that.
`notifyStatusListeners` and `notifyPageRequestListeners` won't work here.
Does **Option 1** in my comment above works for your?

**Comment by ShalikaAshan01** [comment]
hello is this worked for you? 
In my case, This is only working if I scrolled a littlebit. 

`                    
final List<FavoriteListingModel> newList = List<FavoriteListingModel>.of(_pagingController.itemList??<FavoriteListingModel>[]);
newList.removeAt(index);
_pagingController.itemList = newList;
`

This is my code.

**Comment by MoshDev** [comment]
Hi, is this not working anymore? tried 3.1.0 and 3.2.0 and both are not removing items and Option 1 or Option 2 are not working also!
i have to scroll manually to refresh the list and remove the items otherwise they will remain

**Comment by bizk-sato** [comment]
@EdsonBueno Do you have other ways to remove item? 
as @MoshDev Those two options don't work. I have to scroll the list manually to get it removed.
