### ISSUE TITLE
how can i use this package with firestore ?

### ISSUE THREAD

**Issue by jamaltsdm** [EdsonBueno/infinite_scroll_pagination#171]
if possible post an example how can i use this package with firestore

**Comment by aagarcia** [comment]
Someone have this example. Actually need to make this option, but don't have this example.

**Comment by toufiksalhi** [comment]
same issue

**Comment by clragon** [comment]
This issue provides very little information on what is required from us. 
If you would like help, please try asking in the community: https://discord.gg/rflutterdev
