### ISSUE TITLE
Using CupertinoSliverRefreshControl instead of RefreshIndicator

### ISSUE THREAD

**Issue by titovnikita** [EdsonBueno/infinite_scroll_pagination#174]
Hi! I would like to use CupertinoSliverRefreshControl for iOS and RefreshIndicator for Android, but I cannot make it work. It works like a charm with normal ListView, but not with PagedListView. 
```
CustomScrollView(
        slivers: [
          CupertinoSliverRefreshControl(
            onRefresh: _refreshRandomNumbers,
          ),
          _sliverListView,
        ],
      );
```

Sample: https://evanfang.medium.com/how-to-make-your-scrollview-support-pull-to-refresh-864f1b0a02e2

Did anyone make it work? Will appreciate any help.
Thanks!

**Comment by clragon** [comment]
and you are using a `PagedSliverList`?

**Comment by chitgoks** [comment]
I do wish there is an example using PagedSliverList
