### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by Nazarii77** [EdsonBueno/infinite_scroll_pagination#175]
I have added timeouts of 30 seconds on every api call and throw TimeoutException.

In case: I started loading with interned, but the internet was lost  in 30 second It works and shows please try again later. Aftre that I turn on internet and trying again, but the loading goes forever and nothing happens

**Comment by clragon** [comment]
You have to update the state of the PagingController with your error.

**Comment by abdalazeez1** [comment]
try this 
pagingController.error = error
