### ISSUE TITLE
Add item and change item

### ISSUE THREAD

**Issue by kmartins** [EdsonBueno/infinite_scroll_pagination#18]
In sorted pagination, e.g. task list sorted alphabetically by name, how can I add a new item or change the name of the item?

**Comment by EdsonBueno** [comment]
Hi @kmartins , sorry for the delay! I'm on a trip and will be back in a week or so.

Below you can see how to delete an item from the list, the same applies for changing/adding/removing/sorting. Thank you!

**Option 1**
```dart
final newList = List.of(_pagingController.itemList);
newList.removeWhere(...);
_pagingController.itemList = newList;
```

**Option 2**
```dart
_pagingController.itemList.removeWhere(...);
_pagingController.notifyListeners();
```

In short, either you modify a copy of the old list, or you call notifyListeners by yourself.

**Comment by Ham3D** [comment]
hey @EdsonBueno 
I tested both options, but none are working.
I need to to a :

` _pagingController.refresh();`
to see the changes.
imagine a chat app, i need to add new messages on the fly, but so far, i have to refresh on every change.
