### ISSUE TITLE
Cant't add Scrollbar

### ISSUE THREAD

**Issue by sbergmair** [EdsonBueno/infinite_scroll_pagination#182]
How can I add a Scrollbar. In my case I can't pull to refresh, if I add a Scrollbar like `Scrollbar(child: PagedListView(...))`.

**Comment by clragon** [comment]
pull to refresh must have the scrollview as direct child. I am not sure if this is compatible with scrollbar.
You can instead try wrapping the pull to refresh with a scrollbar.

however, this is not an issue with this package.
