### ISSUE TITLE
last page not being added

### ISSUE THREAD

**Issue by abolfazlrezaeiv** [EdsonBueno/infinite_scroll_pagination#184]
When I scroll to the end of the list the last page won't be added
for example, I have 25 element
each page has 6 element
but I can't see the last 6 item
instead, I get "something went wrong......"
at the end of the list
@EdsonBueno

**Comment by clragon** [comment]
We cant help you without further details. 
It seems like your code has thrown an error somewhere. 
If you need additional help please visit the community instead: https://flutter.dev/community
