### ISSUE TITLE
PagedListView inside ListView, unable to re-scroll up to the top of the screen after scrolled down

### ISSUE THREAD

**Issue by giacomok** [EdsonBueno/infinite_scroll_pagination#186]
Hi,  
I put the PagedListView inside another ListView, and I have this strange behaviour: after I scrolled down the PagedListView, when I re-scroll up (and the scroll goes above the PagedListView) the screen is scrolled down automatically until the PagedListView starts.  

I mean, I am not able to re-scroll up to the top of the screen.

**Comment by giacomok** [comment]
It was not related to the package, sorry. I close the issue

**Comment by notufure** [comment]
how to scrolling inside listview
