### ISSUE TITLE
insert newly added item at the top of the list

### ISSUE THREAD

**Issue by MohammedElotol** [EdsonBueno/infinite_scroll_pagination#187]
How can I add new item at the top - or delete- keeping the paged list intact

**Comment by ChiPhanTlm** [comment]
same issue here, any example :D

**Comment by MohammedElotol** [comment]
I made a fork and added `controller. insertItemAt(index, item)`

My fork:
https://github.com/MohammedElotol/infinite_scroll_pagination

**Comment by obrunsmann** [comment]
@MohammedElotol I am also interested in this feature. What about a PR for the main project?

**Comment by EdsonBueno** [comment]
You can always edit the `itemList` directly as shown [here](https://github.com/EdsonBueno/infinite_scroll_pagination/issues/245).
