### ISSUE TITLE
Refreshing clears previous listview

### ISSUE THREAD

**Issue by Veeksi** [EdsonBueno/infinite_scroll_pagination#188]
How should I check before I refresh my listview that I have internet connection because otherwise I lose all that data in previous listview?

**Comment by clragon** [comment]
this is the same issue as #115.
mr edson is unfortunately not interested in adding such a functionality, so you have to do it yourself.

one way of doing that would be overriding the `refresh` method of the `PagingController`:

```dart
@override
Future<void> refresh({bool background = false}) async {
  if (background) {
    try {
      final items = fetchItems(firstPageKey);
      value = PagingState(
        nextPageKey: firstPageKey,
        itemList: items,
        error: null,
      );
      appendPage(items);
    } catch (e) {
      error = e;
    }
  } else {
    super.refresh();
  }
}
```
or alternatively, you could add an extension method, 
like `backgroundRefresh`, to the `PagingController` without the if statement.

**Comment by Veeksi** [comment]
> 

I don't see how this can be used when using state management solution like BLoC where you listen state changes and based on that get results

**Comment by sou1maker** [comment]
@Veeksi  Extends and override these methods to get what you want

```
class PagingControllerExtent<PageKeyType, ItemType>
    extends PagingController<PageKeyType, ItemType> {
  PagingControllerExtent({
    required super.firstPageKey,
    super.invisibleItemsThreshold,
  });

  /// Whether it is in the state of background refresh
  bool background = false;

  @override
  void refresh({bool background = false}) {
    if (background) {
      this.background = true;
      // Since the state of PagingState has too much influence,
      // skip it here and directly notifyPageRequestListeners.
      notifyPageRequestListeners(firstPageKey);
    } else {
      super.refresh();
    }
  }

  @override
  void appendPage(List<ItemType> newItems, PageKeyType? nextPageKey) {
    // Add judgment here
    final previousItems = background ? <ItemType>[] : value.itemList ?? <ItemType>[];
    final itemList = previousItems + newItems;
    value = PagingState<PageKeyType, ItemType>(
      itemList: itemList,
      error: null,
      nextPageKey: nextPageKey,
    );
    // reduction
    background = false;
  }
}
```

**Comment by sou1maker** [comment]
This is a very unofficial practice, so if there is a better way please let me know.

**Comment by sandifb** [comment]
any update ? i have clickable chip, for get new data form API and also filter the list.

**Comment by EdsonBueno** [comment]
Closing as this has nothing to do with the package itself but w/ Flutter usage in general.
