### ISSUE TITLE
manually trigger the next page items request 

### ISSUE THREAD

**Issue by jagmohanJelly** [EdsonBueno/infinite_scroll_pagination#191]
like i want the next API call to be executed after a button click or on the bases of user scroll extent, now it automatically calls the next items request with any action

**Comment by masreplay** [comment]
@jagmohanJelly any idea how to implement this?

**Comment by EdsonBueno** [comment]
Duplicate of https://github.com/EdsonBueno/infinite_scroll_pagination/issues/177
