### ISSUE TITLE
Refresh reloads the page, and scroll up to the first page, how can I update an item without reload the whole pages?

### ISSUE THREAD

**Issue by rehamalraee24** [EdsonBueno/infinite_scroll_pagination#192]
I want to refresh one widget item within the items list, I have to call .refresh() function to update the data, How can I update one widget only or update the list without scrolling to the top and showing the progress indicator?

**Comment by LeGoffMael** [comment]
I think you could update the list of the controller directly:

that's how i deleted an element in the list 

```dart
final list = _pagingController.itemList ?? [];
list.removeWhere((friend) => friend.id == user.id);
setState(() {
  _pagingController.itemList = list;
});
```
