### ISSUE TITLE
android build failed on flutter 3 

### ISSUE THREAD

**Issue by akar995** [EdsonBueno/infinite_scroll_pagination#196]
`
../../../../.pub-cache/hosted/pub.dartlang.org/infinite_scroll_pagination-3.1.0/lib/src/ui/paged_sliver_builder.dart:257:24: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../fvm/versions/stable/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance?.addPostFrameCallback((_) {`

**Comment by EdsonBueno** [comment]
This is now published on version 3.2.0.
Thanks all for spotting this.
