### ISSUE TITLE
Update package to Flutter 3.0 compatible

### ISSUE THREAD

**Issue by gorkemsari** [EdsonBueno/infinite_scroll_pagination#197]
../../Applications/flutter/.pub-cache/hosted/pub.dartlang.org/infinite_scroll_pagination-3.1.0/lib/src/ui/paged_sliver_builder.dart:257:24: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.

**Comment by gorkemsari** [comment]
@EdsonBueno

**Comment by edson-mgm** [comment]
Now published on version 3.2.0.
Thanks all for spotting this!

**Comment by EdsonBueno** [comment]
This is now published on version 3.2.0.
Thanks all for spotting this.
