### ISSUE TITLE
[Feature Request] Add noMoreItemsIndicatorBuilder in PagedChildBuilderDelegate

### ISSUE THREAD

**Issue by ikws4** [EdsonBueno/infinite_scroll_pagination#2]
Thanks for this awesome package! but if it has `noMoreItemsIndicatorBuilder` that it will be great!

**Comment by EdsonBueno** [comment]
Thank you for your message! I’ve never thought about it before and will definitely think about it.
For the mean time, you can use the index provided in the `itemBuilder` to append another widget when you’re building the last one from your list.

**Comment by EdsonBueno** [comment]
Hi @ikws4. This is now added on today's release (2.1.0). Thank you for your suggestion!
https://pub.dev/packages/infinite_scroll_pagination/example#customizing-indicators
