### ISSUE TITLE
RefreshIndicator position and Flutter 3

### ISSUE THREAD

**Issue by kafeleporyg** [EdsonBueno/infinite_scroll_pagination#202]
With Flutter 3:
Refresh indicator, wrapped around a PagedListView with Reverse set to True, is shown on the top of the PageListView.
Would be nice to have the way to show it at the bottom of the list, as it was in Flutter 2.

**Comment by EdsonBueno** [comment]
The `RefreshIndicator` feature isn't part of the package, we do have it in the examples, but it's vanilla Flutter code.
