### ISSUE TITLE
Flutter 3.0.1, screen stuck at first page loading

### ISSUE THREAD

**Issue by igor-chernishenko** [EdsonBueno/infinite_scroll_pagination#206]
Checked both lib v3.1.0 and v3.2.0 - app gets stuck on `PagingStatus.loadingFirstPage` even when valid data was provided.

**Comment by igor-chernishenko** [comment]
From debugging I can tell, that after page is appended something calls rebuild() on the widget, which emits empty state which results it being stuck as if I load first page

**Comment by LaurentiuSimionescu** [comment]
I got the same issue by the way
