### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by timurnav** [EdsonBueno/infinite_scroll_pagination#211]
Please add support for start index for lists and grid

**Comment by clragon** [comment]
this is not a feature that the inbuilt listview or gridview provides,
and I do not see why this package would specifically.

If you need to start your listview at a certain scroll offset, you can do that with the [ScrollController](https://api.flutter.dev/flutter/widgets/ScrollController-class.html),
by scrolling to the desired location or setting it without animating.

**Comment by clragon** [comment]
the underlying implementations of the grid and listviews from flutter do not have such a feature, and therefore this library cant provide it (without adding immense complexity).
If you need grids or lists that can jump to certain indexes, you can search pub for the various packages that do this and then use them in combination with this library.
