### ISSUE TITLE
update flutter_staggered_grid_view: ^0.6.1 on develop,please

### ISSUE THREAD

**Issue by xiaodogaa** [EdsonBueno/infinite_scroll_pagination#214]

**Comment by wilz05** [comment]
waiting for the same, current version has some issues with OutOfMemory exceptions

**Comment by clragon** [comment]
flutter staggered grid has changed alot during versions so upgrading isnt simple. 
instead, staggered grid view could be removed as dependency.

**Comment by wilz05** [comment]
> flutter staggered grid has changed alot during versions so upgrading isnt simple. instead, staggered grid view could be removed as dependency.
> 
true, but basically most of the developers want to have cross axis count to be changed @ the index level.  
like 
 `  staggeredTileBuilder: (int index) => index % 2 == 0
            ? new StaggeredTile.fit(2)
            : new StaggeredTile.fit(1),`

If this/similar functionality can be adopted for the PagedGridView or SilverGrid that would be great.

**Comment by clragon** [comment]
changing the cross axis count cannot be done anymore in the newest version of staggered grid view
and the goal of this package isnt to recreate such a feature.
so regardless of whether the dependency is upgraded or not, this wont be achieved.
