### ISSUE TITLE
The previous widgets are disposed when new widgets are added to PagingController

### ISSUE THREAD

**Issue by vovaklh** [EdsonBueno/infinite_scroll_pagination#215]
All widgets in my PagedGridView are disposed when new widgets are added. Is it possible to keep state of this widgets?

**Comment by clragon** [comment]
The way ScrollViews work is by building and discarding children. Your widgets therefore cannot be kept alive. 
You should hoist any State that they might have above your ScrollView if it has to persist for a longer duration.
