### ISSUE TITLE
Have a way to global config firstPageProgressIndicatorBuilder, newPageProgressIndicatorBuilder and so on.

### ISSUE THREAD

**Issue by huhx** [EdsonBueno/infinite_scroll_pagination#216]
In case that we do not want to use the default firstPageProgressIndicatorBuilder and we have many place need to apply pagination. So apply customize newPageProgressIndicatorBuilder, newPageProgressIndicatorBuilder in every places are duplicate code.

**Comment by clragon** [comment]
you can make your own wrapper that applies those defaults.
