### ISSUE TITLE
Feature Request: Add a way to Override Circular Progress Indicator 

### ISSUE THREAD

**Issue by ghost** [EdsonBueno/infinite_scroll_pagination#220]
I need a native indicator for iOS, i tried using PagedSliverBuilder , i thought this would give me flexibility to override 
but when i check it there is no way to override it...

This is the method
 _firstPageProgressIndicatorBuilder 

this is the class  FirstPageProgressIndicator that simple loads a circularProgress Indicator.

**Comment by Fauzdar1** [comment]
You can override the progress indicator using `builderDelegate`:

```
PagedListView(
  pagingController: _pagingController,
  builderDelegate: PagedChildBuilderDelegate<YourModel>(
    //Visible when the list is empty/first load
    firstPageProgressIndicatorBuilder: (context) =>
      const CustomProgressIndicator(),
    //Visible when loading more items at the bottom of the list
    newPageProgressIndicatorBuilder: (context) =>
      const CustomProgressIndicator(),
    ...
  ),
),
```
