### ISSUE TITLE
Getx Pagination not working properly

### ISSUE THREAD

**Issue by FoloosiApps** [EdsonBueno/infinite_scroll_pagination#222]
Getx Pagination not working properly

Can you please share example source code in getx pagination

**Comment by brunodmn** [comment]
Hello, I did a minimal sample trying to find out an error, here is how I use it with getx: [https://github.com/brunodmn/infinite_scroll_pagination_getx/tree/master/lib](https://github.com/brunodmn/infinite_scroll_pagination_getx/tree/master/lib)
