### ISSUE TITLE
Null check operator used on a null value. Error thrown null.

### ISSUE THREAD

**Issue by Andrushka1012** [EdsonBueno/infinite_scroll_pagination#225]
I got in my crashlitic issue
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
Null check operator used on a null value. Error thrown null.

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown null.
       at PagingController.notifyStatusListeners(paging_controller.dart:170)
       at PagingController.value=(paging_controller.dart:94)
       at PagingController.appendPage(paging_controller.dart:105)
       at PagingController.appendLastPage(paging_controller.dart:114

Looks like _statusListeners is null and  line  if (_statusListeners!.isEmpty) { throw exception

**Comment by ThomasCarrillo** [comment]
Hi,

I got the same issue in my crashlytics :

```
Null check operator used on a null value. Error thrown null.
       at PagingController.notifyStatusListeners(paging_controller.dart:170)
       at PagingController.value=(paging_controller.dart:94)
       at PagingController.error=(paging_controller.dart:69)
```

My non-crash rate is decreasing like a rocket because of this, can you please take a look ?

Thank you in advance 😃

**Comment by AmirMohammadKargar** [comment]
Hi,
I got in my sentry issue

```
paging_controller.dart in PagingController.notifyStatusListeners at line 170 within infinite_scroll_pagination
paging_controller.dart in PagingController.value= at line 94 within infinite_scroll_pagination
paging_controller.dart in PagingController.appendPage at line 105 within infinite_scroll_pagination
paging_controller.dart in PagingController.appendLastPage at line 114 within infinite_scroll_pagination
```

can you please take a look ?

**Comment by EdsonBueno** [comment]
This is fixed[ by this](https://github.com/EdsonBueno/infinite_scroll_pagination/pull/246) PR and will be published in our next release.
