### ISSUE TITLE
default newPageErrorIndicatorBuilder and retryLastFailedRequest don't retry

### ISSUE THREAD

**Issue by mkatzour** [EdsonBueno/infinite_scroll_pagination#226]
First off: Thank you for the excellent package!

When I force a failure on one of my next page requests, both the default newPageErrorIndicatorBuilder widget, as well as a custom one calling retryLastFailedRequest don't trigger a retry. Looking at the code, I see it clears the error, but doesn't notify listeners... could that be why?

My workaround is to use a custom widget like this:
`newPageErrorIndicatorBuilder: (context) =>
   generateRetryButton("Something went wrong. Tap to retry",
   () {
     _pagingController.retryLastFailedRequest();
     _fetchFeedPage(_pagingController.nextPageKey!);
   }, key: const Key("feedNewPageError"))`

Thanks!

**Comment by frankmungnodev** [comment]
I have the same problem too

**Comment by abubakarmvp** [comment]
i am also facing the same problem

**Comment by EdsonBueno** [comment]
You should probably delete that `_fetchFeedPage(_pagingController.nextPageKey!)` line. Can you try again and tell me the result?

**Comment by eastsss** [comment]
Same problem, retryLastFailedRequest() call doesn't do anything at all. Page request listener is not notified.
