### ISSUE TITLE
example can't run

### ISSUE THREAD

**Issue by zonda-alias** [EdsonBueno/infinite_scroll_pagination#227]
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
package identifier or launch activity not found.
Please check /Users/zonda/Documents/Study/infinite_scroll_pagination/example/android/app/src/main/AndroidManifest.xml for errors.
No application found for TargetPlatform.android_arm64.
Is your project missing an android/app/src/main/AndroidManifest.xml?
Consider running "flutter create ." to create one.

**Comment by clragon** [comment]
The example has been updated. Please let us know if you continue to experience issues with it.
