### ISSUE TITLE
[Adding Functionality] Add and Remove item Functionality Missing

### ISSUE THREAD

**Issue by dan15h** [EdsonBueno/infinite_scroll_pagination#228]
There must be an option to add or remove an item to the list within the paging controller. So devs can directly show these items in the list instead of making another call to the server.

**Comment by gysipos** [comment]
Yeah, deleting an item is pretty core functionality

**Comment by EdsonBueno** [comment]
please, see [this](https://github.com/EdsonBueno/infinite_scroll_pagination/issues/245)
