### ISSUE TITLE
Introduce DiffUtil to compare each items before insert

### ISSUE THREAD

**Issue by anderscheow** [EdsonBueno/infinite_scroll_pagination#229]
Currently it is possible to have duplicate items inside the listing. By introducing DiffUtil similar to Android [DiffUtil](https://developer.android.com/reference/kotlin/androidx/recyclerview/widget/DiffUtil.ItemCallback), can prevent same items to be inserted to the listing.

**Comment by clragon** [comment]
There is no reason for this to be part of this package.
If you wish to have a tool to compare you items before adding them to the controller, you can do so from the outside.
There are also many other ways of comparing items in dart, like by overriding the comparison operator. 
This seems to be out of scope.
