### ISSUE TITLE
addPageRequestListener called after hiding the loading indicator

### ISSUE THREAD

**Issue by awnigharbia** [EdsonBueno/infinite_scroll_pagination#23]
Hey @EdsonBueno , Thank you for this awesome library.

I tried your simple example and the fetch is called again once the data is loaded causes to load the second page.

I'm also wondering how to disable the loading indicator when calling the `refresh()` method?

**Comment by EdsonBueno** [comment]
Hi @awnigharbia.
I'm not sure I understood what you said in your first sentence. If I'm right, you're complaining about the second page being requested immediately when the first page is loaded.
That can be solved by increasing the `invisibleItemsThreshold` as indicated [here](https://pub.dev/packages/infinite_scroll_pagination/example#changing-the-invisible-items-threshold).

As for hiding the loading indicator when calling `refresh()`, you can't do that! 
What you can do however, is to **not** call `refresh()`, and instead call directly a function that fetches your first page again.

**Comment by awnigharbia** [comment]
Hi @EdsonBueno ,

I tried to set the `invisibleItemsThreshold` to `1`, however, it's still the same issue I still get the second-page results. 

Anything related I can test for this issue?

**Comment by awnigharbia** [comment]
Hey @EdsonBueno 

I found out my layout is causing this issue!

my layout structure is like this:
`Stack -> ListView -> PagedListView`

However, When I remove the Stack and listview the issue is solved. 

Any idea regarding this issue?

**Comment by awnigharbia** [comment]
I solved it with `CustomScrollView`, but now I'm facing an issue when calling the first page again it appends the data to existing data and makes it duplicates again, How can I replace it?

**Comment by EdsonBueno** [comment]
Instead of using `appendPage` or `appendLastPage` use the value property:

```dart
_pagingController.value = PagingState(
  nextPageKey: secondPageKey,
  error: null,
  itemList: firstPageItemList,
);
```

**Comment by awnigharbia** [comment]
> Instead of using `appendPage` or `appendLastPage` use the value property:
> 
> ```dart
> _pagingController.value = PagingState(
>   nextPageKey: secondPageKey,
>   error: null,
>   itemList: firstPageItemList,
> );
> ```

This works for resetting the `itemList` but it doesn't work when `appendLastPage` called. It'll actually still showing a loading indicator when scrolling down and load the nextPage.

**Comment by EdsonBueno** [comment]
For the last page, 'nextPageKey' should be 'null'.

**Comment by awnigharbia** [comment]
This is my code: 

```js
if (refresh) {
        pagingController.value = PagingState(
          itemList: newItems,
          nextPageKey: 2,
          error: null,
        );
      } else if (isLastPage) {
        // pagingController.appendLastPage(newItems);
        pagingController.value = PagingState(
          itemList: pagingController.itemList + newItems,
          nextPageKey: null,
          error: null,
        );
      } else {
        final nextPageKey = pageKey + 1;

        pagingController.value = PagingState(
          itemList: pagingController.itemList ?? [] + newItems,
          nextPageKey: nextPageKey,
          error: null,
        );
        // pagingController.appendPage(newItems, nextPageKey);
      }
```
The behavior I get is after calling refresh the second page is not loaded and it's infinitely showing the loading indicator. That's my issue here.

**Comment by EdsonBueno** [comment]
I see it now! This is related to [this issue](https://github.com/EdsonBueno/infinite_scroll_pagination/issues/16).
I'll try to figure something out and post the updates there. Ok? Thank you!

**Comment by awnigharbia** [comment]
@EdsonBueno Ok. Thank you, I'll wait for any updates.
