### ISSUE TITLE
Infinite scroll pagination: Package causing issue in list view while scrolling

### ISSUE THREAD

**Issue by Iqra18** [EdsonBueno/infinite_scroll_pagination#230]
Package: Infinite scroll pagination

Currently, the list in the pagination scroll is reshuffled on refresh call and the starting index changes to the incremented value continuously, while it should remain 0 by default(because according to code it has been set to 0)

Kindly provide a possible solution for the same

**Comment by clragon** [comment]
It is difficult for us to figure out your issue from your description.
If you need help with your dart/flutter code, please visit the community instead: https://flutter.dev/community
