### ISSUE TITLE
How to update existed item on list view?

### ISSUE THREAD

**Issue by cogivn** [EdsonBueno/infinite_scroll_pagination#238]
Hi,

Thank you for creating awesome library.
I'm having a problem, how can i update item in specific page when using `infinite_scroll_pagination`

Ex:
Page 0[Rambutan, Tomato, Pear]
Page 1[Apple, **`Orange`**, Cherry]
Page 2[Pipeapple, Mango, Melon]

Update Page 1[Apple, **`Banana`**, Cherry]

Thank you,

**Comment by petodavid** [comment]
How did you manage this? Update?

**Comment by SebastienBtr** [comment]
I would also like to have this feature

**Comment by lukaskris** [comment]
use this one
i think it the only way to update an single item

pagingController.itemList = pagingController.itemList?.map((e) {
        if (e.postId == postId) {
          return e.copyWith(
              pollings: dataResult.pollings, votedId: dataResult.votedId);
        } else {
          return e;
        }
      }).toList();

but it will be janky if u turn on the transition
