### ISSUE TITLE
Dynamic pageKey

### ISSUE THREAD

**Issue by sm2017** [EdsonBueno/infinite_scroll_pagination#24]
Assume we have 1000 items and loaded first page (10 item per page), If user delete one of items, and we load next page with offset  10, we lose an item! is it safe to ignore pageKey and use `_pagingController.itemList.length`?

**Comment by EdsonBueno** [comment]
What's this `pageKey` you're considering ignoring? Can you provide me a code example?

**Comment by sm2017** [comment]
I am taking about

```dart
_pagingController.addPageRequestListener((pageKey) {
      _fetchPage(pageKey);
    });
```

**Comment by sm2017** [comment]
My server implementation is base on integer offset limit

**Comment by EdsonBueno** [comment]
My advice to you is:
Whenever an item is deleted, instead of using the `itemList` setter , use the `value` setter. That way you can change the `nextPageKey` as well:

```dart
pagingController.value = PagingState(
        itemList: NEW_LIST,
        nextPageKey: NEW_LIST.length,
        error: null,
      );
```

**Comment by sm2017** [comment]
@EdsonBueno see https://github.com/EdsonBueno/infinite_scroll_pagination/blob/master/lib/src/core/paging_controller.dart#L85-L87

Are you sure about it? if I delete an item from list (By cloning item too), the status it not changed and `notifyStatusListeners` is not triggered, How you update view?

**Comment by EdsonBueno** [comment]
@sm2017 I like your approach to changing list items – in which you treat the list as immutable.
As for your last comment, you can register three types of listener to a `PagingController`:
1. `addStatusListener`: This one is called when the status is changed. For example, from loading to error.
2. `addPageRequestListener`: Called when a new page is needed.
3. `addListener`: Called when anything changes (`itemList`, `error` or `nextPageKey`).

The third one is the one used by the view to listen for changes.

**Comment by sm2017** [comment]
@EdsonBueno Thanks a lot
Just a little question, Must I be worry about `List<MyType>.from(items);`? I think it can be block thread, What do you think? 
How large must be items to put it in `compute`? 10k? 100k?

**Comment by EdsonBueno** [comment]
I'm not qualified to answer that for you. I'm sorry!

**Comment by Martibis** [comment]
I have another case for a dynamic PageKey, the data I want to return from my MySQL DB is ordered by date as opposed to by id (I guess technically speaking I could convert DateTime to an int, but just being able to use DateTime would be nice). Great package by the way!
