### ISSUE TITLE
Append Page at the beggining

### ISSUE THREAD

**Issue by carrasc0** [EdsonBueno/infinite_scroll_pagination#244]
I have a chat app that use this library inverted naturally, and i would like to add items to the list without rebuild the whole list. Is there any way to append items at the beginning and keeping same page key, instead of at the end?

**Comment by mitesh77** [comment]
@carrasc0  The same issue, I am facing when I have to add a few beginning messages. stick with the same position not rebuild.

have you found any solution @carrasc0?

**Comment by mitesh77** [comment]
when we used chat we had to go sometime on both sides, and I still did not find any solution. @carrasc0 let me know if you have a solution.

**Comment by carrasc0** [comment]
Nothing yet guys. Waiting a response from them yet

**Comment by carrasc0** [comment]
@okaforcj does your changes fix this issue?

**Comment by okaforcj** [comment]
> @okaforcj does your changes fix this issue?

Yeah it does, i forked the repo and added a new api called prependPage which should fix it. I am currently already using it in my app and it works well

**Comment by carrasc0** [comment]
I think they closed it without feedback, which is a very infantil behaviour @okaforcj

**Comment by carrasc0** [comment]
@okaforcj I use your library in production and its great. However, that functionality is quite necessary for a variety of use cases, currently I gotta add the mentioned fix via extensions, but would be nice to add it as a feature.

**Comment by okaforcj** [comment]
hey thanks for the feedback @carrasc0 , i use it in production of my own companys app currently. but i dont know if the authors of this library is accepting PRs from independent devs so I just left it out for now.

**Comment by mitesh77** [comment]
can you provide me with how this add-in project @okaforcj 
`    infinite_scroll_pagination: #^3.2.0
        git:
            url: https://github.com/okaforcj/infinite_scroll_pagination.git
            ref: master
            path: infinite_scroll_pagination`
this not working

**Comment by zahidshaikh08** [comment]
This issue is very important as this lib has been used by so many devs and we 100% this to be fixed and have this feature.
Also there is one issue where if we delete the item from list users must have to scroll above or below to reflect that deleted item from list to be disappear, which is a major bug.

I think the issue for both of this things are because of internal SliverList() which does not refreshed somehow and that is causing these bugs.

**Comment by wildsurfer** [comment]
+1 for this feature

**Comment by n7tequila** [comment]
+1 for this feature

**Comment by Trung15010802** [comment]
+1 for this feature

**Comment by lybur** [comment]
+1 for this feature

**Comment by clragon** [comment]
even if the item was added at the beginning, which you can do by manually manipulating the item list,
this would still cause a rebuild everywhere. it is not possible to modify the list without a rebuild.
