### ISSUE TITLE
How to remove an item properly?

### ISSUE THREAD

**Issue by bizk-sato** [EdsonBueno/infinite_scroll_pagination#245]
I want to remove an item from the list. 

Tried these 2 options below suggested in https://github.com/EdsonBueno/infinite_scroll_pagination/issues/18 but they didn't work.
I had to scroll the list manually, and then it was removed.
I don't want users to scroll manually to remove an item.

Option 1
```
final newList = List.of(_pagingController.itemList);
newList.removeWhere(...);
_pagingController.itemList = newList;
```
Option 2
```
_pagingController.itemList.removeWhere(...);
_pagingController.notifyListeners();
```

**Comment by tomasweigenast** [comment]
Same here! @EdsonBueno

**Comment by MichaelJHodge** [comment]
Not sure if you've tried this yet @bizk-sato, but this works for me:

`_pagingController.remove(object);`

In this case the object is just a record/document that I've retrieved from firebase. Let me know if this helps!

**Comment by sandrocsimas** [comment]
> Not sure if you've tried this yet @bizk-sato, but this works for me:
> 
> `_pagingController.remove(object);`
> 
> In this case the object is just a record/document that I've retrieved from firebase. Let me know if this helps!

PagingController does not have `remove` method, at least in version 3.2.0.

**Comment by MichaelJHodge** [comment]
Apologies! I meant: 

`_pagingController.itemList.remove(object); `

**Comment by rajada1** [comment]
Please provide a code to reproduce the problem.

**Comment by cofedream** [comment]
I have same question, then I try this, it's work for me.

```
void removePageItem(int index,E element){
  _pagingController.itemList?.remove(element);
  _pagingController.notifyPageRequestListeners(index);
}
```

**Comment by Coder7777** [comment]
> remove

The code does not look elegant, but it works.

Thanks

**Comment by AClon314** [comment]
> I have same question, then I try this, it's work for me.
> 
> ```dart
> void removePageItem(E element){
>   _pagingController.itemList?.remove(element);
>   _pagingController.appendLastPage([]); // tigger notify
> }
> ```

Maybe this could be better since the old method won't update the next page anymore.
```dart
void removePageItem(E element){
    controller.pagingController.itemList?.remove(element);
    controller.pagingController.appendPage(<E>[],0); // tigger notify but still can load the nextPage
  }
```
0 is my set initial page number, if your's is 1 then that's 1.

**Comment by enchance** [comment]
> I want to remove an item from the list.
> 
> Tried these 2 options below suggested in #18 but they didn't work. I had to scroll the list manually, and then it was removed. I don't want users to scroll manually to remove an item.
> 
> Option 1
> 
> ```
> final newList = List.of(_pagingController.itemList);
> newList.removeWhere(...);
> _pagingController.itemList = newList;
> ```
> 
> Option 2
> 
> ```
> _pagingController.itemList.removeWhere(...);
> _pagingController.notifyListeners();
> ```

Option 2 worked for me. Do you know of a way to make it animate instead of just suddenly disappearing?
