### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by blueturningred** [EdsonBueno/infinite_scroll_pagination#248]
Last commit was around nine months ago. Many open issues that are not particularly new with no reply from the author/maintainers.

**Comment by EdsonBueno** [comment]
Yes, it is. So sorry for not being responsive on the issues lately. Last commit on master was 9 months ago, but we're working on a new release. Things should start changing by next week.

**Comment by blueturningred** [comment]
Glad to heart that. Keep up the awesome work! ⭐
