### ISSUE TITLE
How can we use skeleton loading on this library. It doesnt seems like working. only lottie or normal loader works

### ISSUE THREAD

**Issue by RahnDev** [EdsonBueno/infinite_scroll_pagination#249]

**Comment by clragon** [comment]
Your question does not include enough details for us to answer it.

Can you please elaborate?
What is skeleton loading?
"It doesnt seems like working" - please tell us exactly what is not working.

**Comment by RahnDev** [comment]
Hi @clragon , we looking to implement this library https://pub.dev/packages/skeletons as loader instead of CircularProgressBar. But after trying its unable to show up properly on first load and also on next page load

**Comment by RahnDev** [comment]
Hi @clragon sorry i found the issue. i missed out on this **shrinkWrapFirstPageIndicators: true,** after adding then i works. so i will close this. sorry for any inconvenience

**Comment by mmercatdev** [comment]
Hi all!

I was starting the integration of this in order to paginate a feed. Previously I had a FutureBuilder, with the future being the query to my backend. Then using the param `initialData` of the FutureBuilder I placed an skeleton while the query was running.

How was the final code used to show some skeleton loader combined with the pagination?

Can you please provide a working example? Thanks in advance!

**Comment by RahnDev** [comment]
Hi @mmercatdev 

Here is example code for our project

**PagedSliverList<int, CatalogueItems?>(
                shrinkWrapFirstPageIndicators: true,
                pagingController: pagings[i],
                builderDelegate: PagedChildBuilderDelegate<CatalogueItems?>(
                  firstPageProgressIndicatorBuilder: (context) => _loader(count: 10),
                  newPageProgressIndicatorBuilder: (context) => _loader(count: 1),
                  firstPageErrorIndicatorBuilder: (context) =>
                      _emptyListingWidget(),
                  noItemsFoundIndicatorBuilder: (context) =>
                      _emptyListingWidget(),
                  animateTransitions: true,
                  itemBuilder: (context, item, index) => _items(item)
                )),**

shrinkWrapFIrstPageIndicators need to be set to true in order for Skeleton under _loader to work. Hope this helps you

**Comment by mmercatdev** [comment]
Thank you very much for that response! Much clear now!
