### ISSUE TITLE
PagedGridView doesn't wait for scroll end?

### ISSUE THREAD

**Issue by Amitbhave** [EdsonBueno/infinite_scroll_pagination#25]
Hi @EdsonBueno ,
Does PagedGridView not wait for scroll to go till end of the screen? Or am I missing something?
Currently it is making API calls pagewise, but not waiting for next page call till I scroll till the end of 1st page.

This is my PagedGridView.
`PagedGridView(
                                pagingController: _pagingController,
                                gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                                  crossAxisCount: 2,
                                  childAspectRatio: 0.65,
                                  crossAxisSpacing: 15,
                                  mainAxisSpacing: 15,
                                ),
                                builderDelegate:
                                PagedChildBuilderDelegate<Product>(
                                  itemBuilder: (context, item, index) =>
                                      ChangeNotifierProvider.value(
                                        value: item,
                                        child: ProductCard(
                                          subcategoryId: widget.subcategoryId,
                                        ),
                                      ),
                                ),
                                shrinkWrap: true,
                                physics: NeverScrollableScrollPhysics(),
                              ),`

`Future<void> _fetchPage(int pageKey) async {
    try {
      final newItems =
          await Provider.of<ProductsProvider>(context, listen: false)
              .fetchProducts(widget.subcategoryId, pageKey);
      final isLastPage = newItems.length < _pageSize;
      if (isLastPage) {
        _pagingController.appendLastPage(newItems);
      } else {
        final nextPageKey = pageKey + 1;
        _pagingController.appendPage(newItems, nextPageKey);
      }
    } catch (error) {
      _pagingController.error = error;
    }
  }`

**Comment by EdsonBueno** [comment]
Hi @Amitbhave .
No, it doesn't wait until the end of the page to request another. It requests another page in advance so that the pagination becomes transparent to the user.
By default, it requests another page when there are 3 items left to be built. You can lower that number as [shown in the cookbook](https://pub.dev/packages/infinite_scroll_pagination/example#changing-the-invisible-items-threshold).
Thank you!
