### ISSUE TITLE
Add example of how to use PagedSliverBuilder with flutter_staggered_grid_view

### ISSUE THREAD

**Issue by erf** [EdsonBueno/infinite_scroll_pagination#253]
I would love to see an example on how to use flutter_staggered_grid_view with PagedSliverBuilder

**Comment by clragon** [comment]
If `AppendedSliverGrid` was exported, maybe under a different library path, it would be alot easier to add custom grids on the fly. 
The same goes for `AppendedSliverChildBuilderDelegate`, making it easier to pagify custom lists.
I think this package might have inbuilt support for `flutter_staggered_grid_view` at some point, considering current developments, but it would still be beneficial to export those tools I believe. What do you think @EdsonBueno?

**Comment by davidoort** [comment]
I'm super interested in any developments in this direction, please share an update if you add this example!

**Comment by EdsonBueno** [comment]
Version 4.0.0 now has a `PagedMasonryGridView` class.
