### ISSUE TITLE
How to handle the duplicates?

### ISSUE THREAD

**Issue by nikiforosper** [EdsonBueno/infinite_scroll_pagination#254]
Using my api, data is added every second
So, page 1 is loaded and it is ok. But when page 2 loads and new data is added, then page 2 contains some of the data from the page 1. 
For example: 

1. Page 1: [1, 2, 3, 4, 5]
2. Load page 2
3. Page 1 = [1, 2, 3, 4, 5]
    Page 2 = [4, 5, 6, 7, 8]

My fetch Data function:
```
Future<void> _fetchPage(int pageKey) async {
    try {
      pg++;
      List<SearchClassified> newClassifieds = await SearchService.searchClassifieds(args, pg);
      bool isLastPage = newClassifieds.length < _pageSize;
      if (isLastPage) {
        _pagingController.appendLastPage(newClassifieds);
      } else {
        final nextPageKey = pageKey + newClassifieds.length;
        _pagingController.appendPage(newClassifieds, nextPageKey);
      }
    } catch (error) {
      if (mounted) {
        _pagingController.error = error;
      }
    }
  }
```

**Comment by clragon** [comment]
you can directly access and set the itemList property of the controller.
you can also remove items from the list you are going to add before adding it, by comparing it against the list of existing items.

**Comment by nikiforosper** [comment]
I resolved this with
` _pagingController.itemList = _pagingController.itemList?.toSet().toList();`

**Comment by clragon** [comment]
please close this issue then.
