### ISSUE TITLE
page flicker when call refresh()

### ISSUE THREAD

**Issue by jasonhe88** [EdsonBueno/infinite_scroll_pagination#255]
when call pagingController.refresh(), page will flicker, is there a way to avoid this?

thanks

**Comment by samtuga1** [comment]
I'm also facing a similar issue. Did you find any solutions yet?

**Comment by jasonhe88** [comment]
> I'm also facing a similar issue. Did you find any solutions yet?

No, just fall back to flutter ListView  :-)

**Comment by samtuga1** [comment]
> > I'm also facing a similar issue. Did you find any solutions yet?
> 
> No, just fall back to flutter ListView :-)

hmmm okay thanks

**Comment by eduardovfaleiro** [comment]
was just having this problem. if you're using futurebuilder, switch to loading everything in the appendLastPage / appendNextPage, then just consume it in the itembuilder
