### ISSUE TITLE
nested ListView

### ISSUE THREAD

**Issue by tas-unn** [EdsonBueno/infinite_scroll_pagination#261]
I immediately get a large list (in json format) with one request. And he's nested. That is:
List
--List
-- -- item from List1
-- -- item from List1
-- -- item from List1
-- -- item from List1
--List2
-- -- item from List2
-- -- item from List2
-- -- item from List 2
-- -- item from List2
-- -- item from List2
--List3
-- -- item from List3
-- -- item from List3
-- -- item from List3
and so on

Because the list is very large (1500), then it is very problematic to show it right away in terms of time.
How to make infinity scroll in this case?

**Comment by clragon** [comment]
the infinite_scroll_pagination package is meant for pagination.
since you receive your data in one go there are no pages and no point in using pagination.
you can use a normal listview or gridview builder instead.

**Comment by vgavrilovikj** [comment]
What about when I am getting the above structured data paginated? How to use it properly?
