### ISSUE TITLE
Can I change "No items found The list is currently empty." to another?

### ISSUE THREAD

**Issue by wiany11** [EdsonBueno/infinite_scroll_pagination#262]
Thanks for the beautiful widget.

I wonder if I can change the widget for the empty list

**No items found**
The list is currently empty

to another one? For example, 

```
PagedListView<int, ...>(
  scrollController: ...,
  pagingController: ...,
  builderDelegate: PagedChildBuilderDelegate<...>(
    itemBuilder: (context, item, index) => ...(...),
    emptyListBuilder: (context) => AnotherWidget(...),
  ),
)
```

**Comment by lucasdidur** [comment]
Any update?

**Comment by lucasdidur** [comment]
If you search for 'No items found' will find a `noItemsFoundIndicatorBuilder: (_) => NoItemsFoundIndicator(),` inside of `builderDelegate`
