### ISSUE TITLE
Pagination inside CustomScrollView and TabBar

### ISSUE THREAD

**Issue by lironiz** [EdsonBueno/infinite_scroll_pagination#265]
Hi,
I have a CustomScrollView, that has a title widget and a TabBar widget. the 2 tabs content is a PagedGridView.
the problem is the 'PageRequestListener' calls all the pages right from the beginning, and not in response to scrolling.
after it finishes loading all the pages, the scroll works as expected, so there's just the pagination-not-really-paginating issue.
is this a known issue? is there a known fix for this?
thank you

**Comment by prologikus** [comment]
just use pull/252/head, devs seems busy

**Comment by lironiz** [comment]
> just use pull/252/head, devs seems busy

thanks. did you mean I should use PagedMasonrySliverGrid? I saw that you reported a bug..

**Comment by prologikus** [comment]
@lironiz yes, i still use that despite the bug i found, you can avoid it by not using very very long items, hope there was a better solution

**Comment by clragon** [comment]
The problem you are encountering is most likely resulting from you setting `shrinkWrap: true` on your `PagedGridView`. This will result in all pages being loaded immediately.
To use a Paged view inside of a sliver protocol like `CustomScrollView` instead use the `PagedSliverGrid`.

**Comment by OnyemaAnthony** [comment]
@prologikus  i get this same bug when i use singleChildScrollview or any scroll widget, will  pull/252/head also fix it or it can only fix for CustomScrollview?

**Comment by omarshokry1811** [comment]
so ? did they reslove that ? 
@prologikus @lironiz

**Comment by prologikus** [comment]
I use this pr in my production, i don't think so

**Comment by clragon** [comment]
The problem you are encountering is most likely resulting from you setting `shrinkWrap: true` on your `PagedGridView`
