### ISSUE TITLE
Unable to set height for noMoreItemsIndicatorBuilder widget

### ISSUE THREAD

**Issue by DizzasTeR** [EdsonBueno/infinite_scroll_pagination#269]
I'm having trouble setting the height for the widget displayed when no more items are available, I tried setting the padding to zero, shrinkWrap to true and setting a SizedBox parent but none seem to do anything, what am I doing wrong?

```dart
@override
  Widget build(BuildContext context) {
    return Obx(() => RefreshIndicator(
          onRefresh: () => Future.sync(
            () => _pagingController.refresh(),
          ),
          child: PagedGridView(
              shrinkWrap: true,
              padding: EdgeInsets.zero,
              pagingController: _pagingController,
              builderDelegate: PagedChildBuilderDelegate<Ad>(
                  itemBuilder: (context, item, index) => AdItem(
                      ad: item, mini: g_ListStyle.value == ListStyle.cell),

                  // Handle no more items widget
                  noMoreItemsIndicatorBuilder: (_) =>
                      SizedBox(height: 10, child: Placeholder())),
                  // --- \\

              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: g_ListStyle.value == ListStyle.card ? 1 : 2,
              )),
        ));
  }
```
<details>
<summary>Screenshot</summary>

![image](https://github.com/EdsonBueno/infinite_scroll_pagination/assets/16344370/9dddbdcf-f18b-4ac8-ba44-0656129c8a58)
</details>

**Comment by hrznx** [comment]
Hello [DizzasTeR](https://github.com/DizzasTeR) are u still alive haha?

**Comment by EdsonBueno** [comment]
@DizzasTeR set the `showNoMoreItemsIndicatorAsGridChild` property of your `PagedGridView` to `false`. 
Feel free to reopen the issue if this doesn't solve the issue.
