### ISSUE TITLE
[Question] PagedSliverList and decoration

### ISSUE THREAD

**Issue by sm2017** [EdsonBueno/infinite_scroll_pagination#27]
How can I set decoration for infinite sliver list, for example, I want to set border radius and background color, or maybe shadow box

**Comment by EdsonBueno** [comment]
The same way you would do it with a `SliverList`. I've found these links:
https://stackoverflow.com/questions/60803149/how-to-corner-radius-on-slivergrid-sliverlist-on-flutter
https://stackoverflow.com/questions/58570208/how-to-give-borderradius-to-sliverlist/63251876#63251876

I hope it helps! Thank you!
