### ISSUE TITLE
Timeline for PagedPageView and PagedMasonryGridView

### ISSUE THREAD

**Issue by sbis04** [EdsonBueno/infinite_scroll_pagination#270]
I found that the `PagedPageView` and `PagedMasonryGridView` is already ready and working in the `develop` branch. Just wanted some updates regarding when it will be released to `pub.dev`.

@edson-mgm looking forward to your response 🙂

**Comment by EdsonBueno** [comment]
They're officially published in the newest 4.0.0 version.
