### ISSUE TITLE
CustomScrollView with cacheExtent causing excessive loading

### ISSUE THREAD

**Issue by Stumblinbear** [EdsonBueno/infinite_scroll_pagination#271]
I'm using the `cacheExtent` property on a `CustomScrollView` in order to keep the size of the scrollbar relatively consistent. This is because each item in my list is not guaranteed to be the same height (there can be relatively large variations). However, this causes the `PagedSliverList` to load items _much deeper_ in the list than is necessary. My scrollbar rarely gets further than halfway down the screen due to the necessity of a large `cacheExtent` (5k-10k pixels).

Is there a way to use the visual location (viewport?) of the end of the list rather than the items that haven't been laid out?

**Comment by clragon** [comment]
`cacheExtent` builds all the items that are inside of its radius; to build the item, they must exist and be requested. They are also laid out, according to the [documentation](https://api.flutter.dev/flutter/rendering/RenderViewportBase/cacheExtent.html). 

Given this, I dont know how what you request could be possible. You are essentially instructing the scrollview to build many items, and therefore many items are built.

**Comment by Stumblinbear** [comment]
Ideally you could `cacheExtent` only items above the viewport, not below. A large `cacheExtent` is necessary for visual scrollbar consistency, but that doesn't have to include the exact same amount of items below the viewport. If this is a limitation of Flutter and not this library, then oke doke
