### ISSUE TITLE
Example breaks on grids

### ISSUE THREAD

**Issue by clragon** [EdsonBueno/infinite_scroll_pagination#278]
The first page key to should actually be `1` and not `0` in these two instances:

https://github.com/EdsonBueno/infinite_scroll_pagination/blob/master/example/lib/samples/beer_masonry_grid.dart#L18
https://github.com/EdsonBueno/infinite_scroll_pagination/blob/master/example/lib/samples/beer_sliver_grid.dart#L19

**Comment by EdsonBueno** [comment]
Solved! Thanks for catching that.
