### ISSUE TITLE
Flutter 3.13 issue: sliver_tools should be upgraded

### ISSUE THREAD

**Issue by kamranbekirovyz** [EdsonBueno/infinite_scroll_pagination#282]
I would like to draw your attention to an issue that has been opened for the 'sliver_tools' package. You can view the details of the issue by visiting the following link: [Issue #85 for sliver_tools](https://github.com/Kavantix/sliver_tools/issues/85).

The issue at hand is causing an error while building and running Flutter projects. This stems from the fact that the 'infinite_scroll_pagination' package relies on an outdated version of 'sliver_tools' (version 0.2.9). Unfortunately, this version is incompatible with the recently released Flutter version 3.13.0.

The problem has already been resolved in 'sliver_tools' version 0.2.11. To address this compatibility issue, I kindly request that you consider upgrading the 'sliver_tools' package to version 0.2.11.

**Comment by EdsonBueno** [comment]
You have to depend on our latest version (4.0.0), which depends on **sliver_tools** 0.2.12.
