### ISSUE TITLE
why don't use SliverAlignedGrid to make height of gridView depend on height of children 

### ISSUE THREAD

**Issue by fahmyabada** [EdsonBueno/infinite_scroll_pagination#284]
if i have dynamic height to child and i not want use Staggered Grid View but i want to height of first child equal height second child if first greater than second then height of second child equal height first child

**Comment by fahmyabada** [comment]
PagedSliverBuilder in custom layout in example package not defined

**Comment by CHPisces** [comment]
The height of each of my grid is dynamic，what should i do.
