### ISSUE TITLE
PagedMasonryGridView Indicator NOT CENTERED, instead it's inserted inside grid

### ISSUE THREAD

**Issue by tovidd** [EdsonBueno/infinite_scroll_pagination#288]
I want to customize the footer of `PagedMasonryGridView` by specify it's `noItemsFoundIndicatorBuilder` & 
`noMoreItemsIndicatorBuilder`.

But lookslike the footer is inserted together with grid children.

<img width="246" alt="Screenshot 2023-09-13 at 16 02 05" src="https://github.com/EdsonBueno/infinite_scroll_pagination/assets/38039123/8eeb63ce-c5d5-4168-82a6-06aafdb0464f">

i tried give top padding, but not works.
```
noMoreItemsIndicatorBuilder: (_) => Padding(
  padding: const EdgeInsets.only(top: 100),
  child: const ListFooter(),
),
```

I was expect that footer is centered in the middle, like the figma design below.

<img width="412" alt="Screenshot 2023-09-13 at 16 10 24" src="https://github.com/EdsonBueno/infinite_scroll_pagination/assets/38039123/ae17280d-a5ff-44c5-89b6-89acc29ad8e0">

I really hope for your help, many thanks.

infinite_scroll_pagination: ^4.0.0
flutter v3.13.3 (stable)

**Comment by clragon** [comment]
Usually, the paged widgets have these parmaters:

```
    this.showNewPageProgressIndicatorAsGridChild = true,
    this.showNewPageErrorIndicatorAsGridChild = true,
    this.showNoMoreItemsIndicatorAsGridChild = true,
```

to specify the behaviour you desire.
This is not the case for the `PagedMasonryGridView` right now.

You can follow the PR at #252 which would address this as well.

**Comment by tovidd** [comment]
i haven't try that but i found `PagedMasonryGridView` cannot be combined with CustomScrollView. Because it will create 2 different scroll view port. if set physics to NeverScrollableScrollPhysics then the `PagedMasonryGridView` cannot be scroll to the end of the list. And `NestedScrollView` also can't make `PagedMasonryGridView` work properly. So i switched to https://pub.dev/packages/pull_to_refresh_flutter3. 

did you get my point, i hope so because my english too poor.

**Comment by clragon** [comment]
Yes. `PagedMasonryGridView` is currently lacking the `PagedMasonryGrid` version which works with `CustomScrollView`.
The PR I mentioned adds that and allows centering the loading indicators. 
However, we must wait for mr edson bueno to merge and release it.

**Comment by clragon** [comment]
I am not sure what you mean by that. 
If you are experiencing an unrelated issue, please open a new issue with detailed instructions, screenshots and code instead. 
thank you.
