### ISSUE TITLE
[Feature request] New PagedPositionedListView widget for scrolling to list item

### ISSUE THREAD

**Issue by vladsonkin** [EdsonBueno/infinite_scroll_pagination#291]
Currently, if we want to scroll to a specific position, we can pass ScrollController and then set the needed position.
However, it works only if the height of the items remains the same. If it's dynamic, then it's impossible to calculate the needed height to scroll.

It was a problem in the ListView widget too and they came up with a new widget [ScrollablePositionedList](https://pub.dev/packages/scrollable_positioned_list) to solve this issue.

It behaves a lot like ListView, so I guess we can create a new widget PagedPositionedListView, which will be a copy of the existing PagedListView but will use ScrollablePositionedList.

**Comment by clragon** [comment]
I prefer https://pub.dev/packages/anchor_scroll_controller which is independant of the view itself, 
and therefore much more versatile.
