### ISSUE TITLE
Separators are not supported, despite docs saying they are

### ISSUE THREAD

**Issue by NoBrainer** [EdsonBueno/infinite_scroll_pagination#297]
There's an [example for separators](https://pub.dev/packages/infinite_scroll_pagination/example#separators), but this feature does not exist in 4.0.0. Am I missing something?

**Comment by clragon** [comment]
[PagedListView.separated](https://pub.dev/documentation/infinite_scroll_pagination/latest/infinite_scroll_pagination/PagedListView/PagedListView.separated.html)

Still exists in version 4.0.0 just like in the example.
What issue are you experiencing?

**Comment by NoBrainer** [comment]
False alarm. It wasn't working, because I missed the `.separated(` part of the example.

Feel free to close the ticket. (I'm not sure if you want it marked as "completed" or "not planned".

**Comment by tiltmaster** [comment]
> False alarm. It wasn't working, because I missed the `.separated(` part of the example.
> 
> Feel free to close the ticket. (I'm not sure if you want it marked as "completed" or "not planned".

does it work or not? because i cant seem to get it to work

**Comment by NoBrainer** [comment]
It works for me. (I recommend copy-pasting the example and tweaking it to make sure you don't miss something.)
