### ISSUE TITLE
Toggle favourite status?

### ISSUE THREAD

**Issue by mohadel92** [EdsonBueno/infinite_scroll_pagination#299]
i can't handle how to toggle changes on already loaded data in the pagecontroller
is there is a recommended way to handle changes inside current data loaded inside controller?

**Comment by caiombueno** [comment]
Hi @mohadel92 .

If you want to manually manage the state of the `PagingController`, you can use the `value` setter of the `PagingController` and assign a `PagingState` to it.

```
_pagingController.value = PagingState(
      itemList: myItemList,
      nextPageKey: nextPageKey,
      error: null, // Or an error, if any.
    );
```

I hope this helps to solve your problem.

**Comment by braincreator** [comment]
_pagingController.value = PagingState(
      itemList: myItemList,
      nextPageKey: nextPageKey,
      error: null, // Or an error, if any.
    );
it's not working, updating itemList, does not refreshing view

**Comment by caiombueno** [comment]
hi @braincreator. Sorry for the late response. 
Try updating the state of the widget.
