### ISSUE TITLE
PagedGridView error indicator and progress indicator show as one of the grid items

### ISSUE THREAD

**Issue by ketkar203040** [EdsonBueno/infinite_scroll_pagination#3]
Thanks for the awesome package. Its perfect for my use case. 

I have found an issue with the `PagedGridView`. The indicators appear at the bottom left and not in the bottom center like in `PagedListView`.

This only happens when `crossAxisCount` is more than 1.

Please check the image below.
## Example
![exampleimage](https://user-images.githubusercontent.com/38080800/94988911-4ec59a80-058e-11eb-87e3-065e45f0814c.jpeg)

**Comment by EdsonBueno** [comment]
That's actually intended behaviour! The reason for that is signalling the user that an error happened fetching that item, or (in the case of a progress indicator) indicate that the items is being fetched.
But I get that it may not be what you want. So I’ll consider parametrizing it for the future. That way everyone's happy. What do you think?

**Comment by EdsonBueno** [comment]
Hi @ketkar203040. This is now added on today's release (2.1.0).
https://pub.dev/packages/infinite_scroll_pagination/example#positioning-grids-status-indicators
