### ISSUE TITLE
pagination happens even not scrolling

### ISSUE THREAD

**Issue by SeasonLeee** [EdsonBueno/infinite_scroll_pagination#30]
hi, thanks for this awesome package and that detailed and funny post about how to use it, but I have a problem that, when this `CommentMessageList` widget initState(come to life or visible to user), that network request(used to load data) happens couple times! (without user scrolling but to my understanding of the mechanism of how this package work, the data requesting should only happen when user scroll to a certain point of the list... right?

I don't know if it's the way how we 'turn page' break the underline pagination or anything... but that shouldn't happen, I guess...

Well, I have a list with length of 7, and the pagination in this case will be happening twice, right?

And this two network requesting happen all at once, once the user is entering the page containing this widget, and there's definitely no scrolling happened yet(because just enter the page.... and the data barely loaded...)

Why?

By the way, the way we 'turn page' is not to use pageNumber or anything that can be calculated, but to use the `ts`(a timestamp value) from the last element of the last list from the last request...

Why we 'turn page' in this way is because the list is dynamic, meaning each element have the possibility to be deleted... and when it delete, in the backend, there'll be a row of record missed, hence the pageNumber will be incorrect...

Not sure if it's how we paginate cause the problem... 

And I paste the code below, hopefully you can help me a little bit here, thanks in advance!

```dart
class CommentMessageList extends StatefulWidget {
  @override
  _CommentMessageListState createState() => _CommentMessageListState();
}

class _CommentMessageListState extends State<CommentMessageList> {
  List<CommentMessage> _commentMessageList;

  int _commentMessageListTotal;

  String lastPageLastItemTs;

  final _pagingController = PagingController<String, CommentMessage>(
    // pageNumber: 1 (we call pageNumber while this package call it pageKey)
    firstPageKey: '',
  );

  @override
  void initState() {
    super.initState();
    _pagingController.addPageRequestListener((pageKey) {
      _getCommentMessageList(pageKey);
    });
  }

  @override
  void dispose() {
    _pagingController.dispose();
    super.dispose();
  }

  Future<void> _getCommentMessageList(String ts) async {
    try {
      Response res = await request.getWithToken(api.getCommentMessage, arg: {
        'pageSize': '5',
        'ts': ts == '' ? null : ts,
      });

      final commentMessageListRaw = commentMessageListRawFromJson(res.body);

      _commentMessageListTotal =
          _commentMessageListTotal ?? commentMessageListRaw.data.total;

      final isLastPage =
          _pagingController.itemList?.length == _commentMessageListTotal;

      // //TODO: complete this error throwing logic later
      // if (commentMessageListRaw.success) {
      //   if (commentMessageListRaw.errorCode != '0') {
      //     throw Error();
      //   }
      // }

      print('total === $_commentMessageListTotal');
      print('length == ${_pagingController.itemList?.length}');

      if (isLastPage) {
        _pagingController.appendLastPage(commentMessageListRaw.data.list);
      } else {
        lastPageLastItemTs = _commentMessageListTotal == 0
            ? ''
            : commentMessageListRaw.data.list?.last?.ts;
        _pagingController.appendPage(
            commentMessageListRaw.data.list, lastPageLastItemTs);
      }
    } catch (error) {
      print(error);
      debugPrint(error);
      _pagingController.error = error;
    }
  }

  @override
  Widget build(BuildContext context) {
    return PagedListView(
      padding: EdgeInsets.only(top: 16),
      pagingController: _pagingController,
      builderDelegate: PagedChildBuilderDelegate<CommentMessage>(
        itemBuilder: (context, commentMessage, index) =>
            CommentMessageListItem(commentMessage: commentMessage),
        noItemsFoundIndicatorBuilder: (context) => PlaceholderMailboxFry(),
        newPageErrorIndicatorBuilder: (context) => Padding(
          padding: const EdgeInsets.all(16.0),
          child: Center(
            child: Text('Something wrong'),
          ),
        ),
        noMoreItemsIndicatorBuilder: (context) => Padding(
          padding: const EdgeInsets.all(16.0),
          child: Center(
            child: Text('Finished'),
          ),
        ),
      ),
    );
  }
}
```

**Comment by EdsonBueno** [comment]
Hi @SeasonLeee, thank you for your feedback!
The only scenario in which the package will trigger a second request is if the first page widgets are not able to fill up the entire screen and still leave a couple of items hidden.

Did you try increasing your page size to see if it still happens? From what I can see, every page of your has 5 items, try working with 15 instead.
If the problem still continues after that, I'll need a toy project I can debug. Try mocking the `request.getWithToken` so that it'll return fake data.
I'll close the issue for now. Once you have your toy project, please reach me on [our chat](https://gitter.im/infinite_scroll_pagination/community).
Thank you so much!

**Comment by SeasonLeee** [comment]
Yeah, currently this is not that a big problem(not crashing app or anything but still, is a existing problem)

And we have other priority at the moment(deadline waving hand....) so I will make a toy project regarding the issue and I will @ you in that chat room you mentioned.

However, I discover another issue which is kind of a big deal, and I hope you can give it a minute, thank you in advance!

The issue I was talking about is this: #31 thanks!
