### ISSUE TITLE
The Custom Layout section of the Cookbook has not been updated with the changes in version 4.0.0.

### ISSUE THREAD

**Issue by MrLepage** [EdsonBueno/infinite_scroll_pagination#301]
Cookbook still mention `PagedSliverBuilder` which has been replaced by `PagedLayoutBuilder`: 
[Custom Layout section in Cookbook](https://pub.dev/packages/infinite_scroll_pagination/example#custom-layout)

**Comment by clragon** [comment]
The section has been updated. thank you.

**Comment by Zvnimir** [comment]
[Custom Layout section in Cookbook](https://pub.dev/packages/infinite_scroll_pagination/example#custom-layout) still shows PagedSliverBuilder instead of PagedLayoutBuilder.
