### ISSUE TITLE
pagedpageview can't scroll in desktop web

### ISSUE THREAD

**Issue by nicelogic** [EdsonBueno/infinite_scroll_pagination#307]
mobile web is ok

**Comment by caiombueno** [comment]
hi @nicelogic, I've tested it, and it works just fine for me. Can you provide some code?

**Comment by nicelogic** [comment]
hi, @caiombueno 
the default behavior for scrolling in a PageView widget is to respond to touch events, not mouse drag events. However, starting from Flutter 2.5.0, the framework introduced device-based dragging for scrolling to better match platform expectations. By default, dragging to scroll with a mouse is disabled on desktop. 
so  i need to modify the scroll behavior of my application, it's my responsibility
i will close this issue
