### ISSUE TITLE
[Question] Disable Automatic Next Page Load

### ISSUE THREAD

**Issue by avishail** [EdsonBueno/infinite_scroll_pagination#309]
Is it possible to replace the "automatic next page load" functionality with a "load next page" button so the next page load will be driven by explicit user action?

I have a use-case where loading the next page is very expensive and I want this to happen only if the user really wants to see the next page.

Thanks!

**Comment by nandakista** [comment]
I have the same issue

**Comment by clragon** [comment]
Duplicate of #177
