### ISSUE TITLE
[Feature Request]: Auto scroll/slide PagedPageView children

### ISSUE THREAD

**Issue by RB-93** [EdsonBueno/infinite_scroll_pagination#316]
There should be a callback function or utility option to auto-slide pageViews. 
It is expected to have autoPlay duration functionality for explicitly giving time duration.

**Comment by clragon** [comment]
Hi, thank you for your issue. 
Such functionality is out of scope for this package and should be implemented from the outside, e.g. via ScrollController.
Thank you.
