### ISSUE TITLE
Infinite Staggered View

### ISSUE THREAD

**Issue by jcdfusion** [EdsonBueno/infinite_scroll_pagination#317]
How can one achieve a Staggered page layout where a tile can occupy 1 to n columns with this package? I saw in this similar issue that it was [advised to use PagedMasonrySliverGrid](https://github.com/EdsonBueno/infinite_scroll_pagination/issues/259#issuecomment-1682966667), but this class is not included in 4.0.0 without specifically requesting the developer branch in the pubspec.yaml, and there doesn't appear to be a way to specify different widths for the items in itemBuilder. Could something like this be achieved using infinite_scroll_pagination? I am not able to find much information on `PagedMasonrySliverGrid` in the documentation. Which page view is appropriate for this case?

Here's an example of the layout I am referring to. In this example we would have a `crossAxisCount` of 3, the red block represents an item that takes up 3 of 3 columns and green takes up 2 of 3, blue 1 of 3:

![image](https://github.com/EdsonBueno/infinite_scroll_pagination/assets/19735935/5dd0e2f9-1d97-4372-a80f-4ea426cd0b2d)

I appreciate any help on this.

**Comment by clragon** [comment]
the `infinite_scroll_pagination` package is a wrapper around existing layouts.
it does not provide new layout widgets. there is currently no widget in the package that wraps another widget which is capable of the functionality you are looking for. 
`PagedMasronyGridView` is a widget from the [`flutter_staggered_grid_view`](https://pub.dev/packages/flutter_staggered_grid_view) package.

**Comment by jcdfusion** [comment]
Yes, the layout I am referring to is from the flutter_staggered_grid_view. Specifically, StaggeredGrid using StaggeredGridTile.
