### ISSUE TITLE
How can i do offline search/filter?

### ISSUE THREAD

**Issue by TrungSE** [EdsonBueno/infinite_scroll_pagination#318]
Searching/Filtering/Sorting only show how to do this with api

**Comment by clragon** [comment]
There should be nothing preventing you from using the exact same code with whatever function you need.

**Comment by Trung15010802** [comment]
> There should be nothing preventing you from using the exact same code with whatever function you need.

Sorry. I think you should open disscussion section. Can i get a sample code of how to achive this?
