### ISSUE TITLE
Using this package with nestedscrollview/tab bars causes issue with scrolling

### ISSUE THREAD

**Issue by fennel-ptorchia** [EdsonBueno/infinite_scroll_pagination#319]
When using this to render a paginated list inside of a nestedscrollview with tabs, going to another tab and then back to the tab with paginated list causes the list to be shown from the beginning, not maintaining the view before moving to a different tab. is there a way to scroll to the previous position or to maintain the position with nested views?

**Comment by clragon** [comment]
TabBarViews not retaining the state of their children is an issue unrelated to this package and has simply to do with how the framework works. This issue applies to any scrollview. There are workarounds for this but I cannot recommend anything specific. 
Please consult the [community resources](https://discord.gg/rflutterdev) instead.

**Comment by fennel-ptorchia** [comment]
That is not the case, they maintain state and scroll position for all except the tab utilizing this package.

**Comment by clragon** [comment]
Could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?
