### ISSUE TITLE
Plans for new release

### ISSUE THREAD

**Issue by Windisch94** [EdsonBueno/infinite_scroll_pagination#321]
Hi - there are quite some new cool features which i would like to have (for example the PagedMasonrySliverGrid) 
are there any plans for a new release? 

Will use a fork for now but would be interesting if and when there will be a new release

**Comment by clragon** [comment]
I am still looking to add another grid type before scheduling a release.
This will probably take another couple weeks.

**Comment by clragon** [comment]
scheduled a new release
