### ISSUE TITLE
Is it possible to insert a new item with animation?

### ISSUE THREAD

**Issue by liujian-930212** [EdsonBueno/infinite_scroll_pagination#323]
Just like  AnimatedList does, insert or delete an item with an animation. If [infinite_scroll_pagination] has this feature, that would be asesome.

Thanks

**Comment by clragon** [comment]
Hi,
Animating insertion or deletion of items is not the responsibility of this package, but rather the scrollview itself.
You can make a PagedAnimatedList yourself with the components in the package.
Maybe someday we get around to adding it to the package directly. There is an issue for that here: #21
Best regards!
