### ISSUE TITLE
how to remove an item

### ISSUE THREAD

**Issue by liujian-930212** [EdsonBueno/infinite_scroll_pagination#325]
I tried to use itemList setter to remove an item, and it seemed worked fine. 

But an RangeError occurred when ‘too many items’ were removed unless refresh the whole PagedListView every time, which is laggy.

Is there a safe way to do so?

Thanks

**Comment by clragon** [comment]
you have to copy the list safely when removing items.

```dart
pageController.itemList = pageController.itemList.toList().where((e) => /* some condition */ );
```
this will correctly update the state, as we are using `toList` to create a new list before assigning it.

**Comment by ke112** [comment]
bool removeItem(T item) {
    pagingController.itemList = pagingController.itemList?.toList()?..remove(item);
    return true;
  }


I wrote this, it's wrong

**Comment by ojpro** [comment]
For anyone want to do it in the new version (^5.1.1) :

```dart
pagingController.value = pagingController.value.filterItems((object) => object.id != item.id);
```
