### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by hacker1024** [EdsonBueno/infinite_scroll_pagination#33]
With null safety increasing in popularity, it'd be great if this package could implement it.

**Comment by Sameerkash** [comment]
I would like to take this up if no one is working on it.

**Comment by EdsonBueno** [comment]
I'm working on it @Sameerkash!

**Comment by Sameerkash** [comment]
@EdsonBueno okay. Cool!

**Comment by joseiriarte1982** [comment]
I still don't get how to use it with my current http request. Si hablas español me refiero que a donde pongo mi request al server, y como implemento el snapshot.data

**Comment by EdsonBueno** [comment]
Done, guys!
https://github.com/EdsonBueno/infinite_scroll_pagination/releases/tag/v3.0.0-nullsafety.0
