### ISSUE TITLE
Fatal Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by matmicro** [EdsonBueno/infinite_scroll_pagination#330]
Version: 4.0.0

```
Fatal Exception: FlutterError
Null check operator used on a null value
```

```
          Fatal Exception: FlutterError
0  ???                            0x0 PagingController.notifyStatusListeners + 170 (paging_controller.dart:170)
1  ???                            0x0 PagingController.value= + 94 (paging_controller.dart:94)
2  ???                            0x0 PagingController.appendPage + 105 (paging_controller.dart:105)
3  ???                            0x0 ForumCategoryPage._fetchPage + 41 (forum_category_page.dart:41)
```

File:  /lib/src/core/paging_controller.dart

Code to fix:
`if (_statusListeners!.isEmpty) {
`

Is it possible to push a fix for this ?
I am facing regularly this issue, almost on iOS.

**Comment by clragon** [comment]
A new release is scheduled for whenever Edson Bueno finds time. We cannot guarantee any timeline. 
Thank you.

**Comment by fizz-viva** [comment]
@EdsonBueno we're waiting for the new release which is gonna fix this issue. Hope you'll get some time for it and we'll get rid of the tons of bug reports. Thanks in advance.

**Comment by SdxCoder** [comment]
I think we should clone this repo and add it under flutter community packages for better support. We are getting crashes on our production app for 6 months now. And single issue is not getting fixed.

@clragon 
@EdsonBueno

**Comment by clragon** [comment]
A new version of the package has been released and this issue should now be fully resolved.
