### ISSUE TITLE
Does it support multiple SliverList?

### ISSUE THREAD

**Issue by aboyo** [EdsonBueno/infinite_scroll_pagination#333]
Hi,
I want to place two SliverList in a CustomScrollView, and start loading the second SliverList when I scrolls to the bottom.
```
CustomScrollView(
        slivers: <Widget>[
          BeerSearchInputSliver(
            onChanged: (searchTerm) => _updateSearchTerm(searchTerm),
          ),
          PagedSliverList<int, BeerSummary>(
            pagingController: _pagingController,
            builderDelegate: PagedChildBuilderDelegate<BeerSummary>(
              animateTransitions: true,
              itemBuilder: (context, item, index) => BeerListItem(
                beer: item,
              ),
            ),
          ),
         PagedSliverList<int, BeerSummary>(
            pagingController: _pagingController2,
            builderDelegate: PagedChildBuilderDelegate<BeerSummary>(
              animateTransitions: true,
              itemBuilder: (context, item, index) => BeerListItem(
                beer: item,
              ),
            ),
          ),
        ],
      );
```
Does it support multiple SliverList?

thx!

**Comment by clragon** [comment]
When `_pagingController` has gotten its last page, it will no longer add items and `_pagingController2` will load items.
If this is what you want, that is indeed possible.

**Comment by aboyo** [comment]
> When `_pagingController` has gotten its last page, it will no longer add items and `_pagingController2` will load items. If this is what you want, that is indeed possible.

Hi,
But wheb I do this, both `_pagingController ` and `_pagingController2`'s PageRequestListener() will be triggered at the same time.

**Comment by clragon** [comment]
They would be triggered both once at the very beginning, yes. But I believe they should otherwise behave as expected?

**Comment by clragon** [comment]
in that case you will have to manually insert the second list once the pagination status of the first controller is completed.
