### ISSUE TITLE
Page layout with header, footer, and floating buttons

### ISSUE THREAD

**Issue by dibenedetto** [EdsonBueno/infinite_scroll_pagination#334]
I would like to create a page with the following layout, which is basically a column:

[top] Header Widget (fixed on page, non-scrollable)
[mid] PagedListView (scrollable) with RefreshIndicator and (one) anchored FloatingActionButton
[bot] Footer Widget (fixed on page, non-scrollable)

But I am having throubles with it... any help is kindly appreciated.

If it is for help, this page is created within a tab page inside a scaffold.

**Comment by clragon** [comment]
Hi!
Your issue would be better fit for the flutter community resources than our github repository, where we mainly focus on fixing bugs or introducing new features. We do not provide support on general integration of the package into your codebase.
You can find the community [here](https://flutter.dev/community).
Thanks!
