### ISSUE TITLE
error G4127D1E8: The getter 'headline6' isn't defined for the class 'TextTheme'

### ISSUE THREAD

**Issue by makhloughi** [EdsonBueno/infinite_scroll_pagination#337]
it seems flutter has been updated and this package is not. and is causing errors in a big project i have used it

**Comment by yuroyami** [comment]
This is causing me an issue as well. Please update!

**Comment by clragon** [comment]
an update is in the works. thank you.

**Comment by clragon** [comment]
A new minor for the package has been rolled out. I hope this resolves your issue.
