### ISSUE TITLE
I delete an element from the feed stream

### ISSUE THREAD

**Issue by ke112** [EdsonBueno/infinite_scroll_pagination#341]
I want to delete a certain element from the infinite feed stream and refresh the display normally. Now the situation is that the last one disappears after deletion, scroll for a while, and the display is normal again. How to solve it  , Here's how

bool removeItem(T item) {
    bool result = dataList.remove(item);
    if (result == false) return false;
    pagingController.itemList = dataList;
    notifyData();
    return true;
  }

**Comment by luckycreationsindia** [comment]
Same issue here,

I'm changing the content of the list (add, delete). How to notify those changes?

**Comment by clragon** [comment]
to correctly notify the controller of the changes, a new list has to be created.
See here: [related Stackoverflow issue](https://stackoverflow.com/a/70771364/7592870).

**Comment by luckycreationsindia** [comment]
I tried creating uniquekey but the scroll position changes.

> Create new PagedListView with around 20 items which can be scrolled down
> Add or remove the element
> Set new uniquekey
> It will scroll to top (Expected - Scroll position should not change)

May be I'm doing something wrong here or I might missed something?
