### ISSUE TITLE
[Bug] Wrong order in example - super.initState(); at the end of initState()

### ISSUE THREAD

**Issue by AdamTechAcc** [EdsonBueno/infinite_scroll_pagination#347]
### Steps to reproduce

Example from pub.dev:

```dart
  @override
  void initState() {
    _pagingController.addPageRequestListener((pageKey) {
      _fetchPage(pageKey);
    });
    super.initState();
  }
```

### Expected results

Good practice is having super.initState(); first in initState();

### Actual results

Wrong order in initState() from example.

### Package Version

4.0.0

### Platform

Android, iOS

### Code sample

<details open>
<summary>Code sample</summary>

```dart
[Paste your code here]
```
</details>

### Logs

<details open>
<summary>Logs</summary>

```console
[Paste your logs here]
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[Upload media here]
</details>

**Comment by clragon** [comment]
thank you for reporting this. it has been fixed.

**Comment by AdamTechAcc** [comment]
Thank You!
