### ISSUE TITLE
Force call on refresh.

### ISSUE THREAD

**Issue by umuieme** [EdsonBueno/infinite_scroll_pagination#35]
When doing a search, if the API call takes time then only the first call to `refresh()` makes the loading appear and all the subsequent calls to `refresh()` are ignored until the error or the page is appended. In perfect case this works fine with debounce as in the search example, but if the API call is delayed then the search API call will get lost.
Is there any way to achieve it as of now?

**Comment by EdsonBueno** [comment]
Hi @umuieme .
The purpose of `refresh()` is to reset `PagingController` to its initial state. If the `PagingController` is already in its initial state, there's nothing left for `refresh()` to do.

In your scenario specifically, even if the pages were being requested every time, you would still have no way of guaranteeing you would also receive the responses in the same order.

I advise you to manage your search calls without relying on `addPageRequestListener`.

Thank you!
