### ISSUE TITLE
Can not find NoMoreItemsIndicator

### ISSUE THREAD

**Issue by edwin-alvarez** [EdsonBueno/infinite_scroll_pagination#36]
@EdsonBueno , Let me start with thanks for sharing your great work with the rest of us, quick question, I'm using 2.2.3. I cannot find NoMoreItemsIndicator class introduced in (2.1.0), I would like to override all IndicatorBuilder so we can provide globalization.

Should NoMoreItemsIndicator be a child class of FirstPageExceptionIndicator?

**Comment by EdsonBueno** [comment]
Hi @edwin-alvarez.
I think nothing changed about that.
In order to change the no more items indicator, you just have to provide a value for the `noMoreItemsIndicatorBuilder` property of the `PagedChildBuilderDelegate` class.
