### ISSUE TITLE
SliverPadding

### ISSUE THREAD

**Issue by sm2017** [EdsonBueno/infinite_scroll_pagination#37]
@EdsonBueno When I wrap `PagedSliverList` with `SliverPadding` to add some padding, the `PagedSliverList` ignore scrolling and fetch all pages infinitely 
There is no other option to add padding

**Comment by EdsonBueno** [comment]
It works perfectly if I add a `SliverPadding` to **character_sliver_list.dart** in the example project.
Your issue is probably elsewhere.
