### ISSUE TITLE
Padding property causing scroll

### ISSUE THREAD

**Issue by rulim34** [EdsonBueno/infinite_scroll_pagination#40]
The bottom padding property of the PagedListView causes loadings builder to be scrollable, but not the top padding.

`child: PagedListView.separated(
    padding: const EdgeInsets.fromLTRB(15, 5, 15, 90),
    builderDelegate: ......,
)`

https://user-images.githubusercontent.com/48084535/104989847-ed96d980-5a4d-11eb-98a0-d6f2f3ecf03a.mp4

**Comment by EdsonBueno** [comment]
Hi @rulim34 .
Try setting `shrinkWrap` to `true`.
```
child: PagedListView.separated(shrinkWrap: true, padding: const EdgeInsets.fromLTRB(15, 5, 15, 90), builderDelegate: ......, )
```

Please, tell me if it works for you!

**Comment by rulim34** [comment]
Thanks, it works. But now, how to make the error builder height fill the screen?

**Comment by EdsonBueno** [comment]
If you want your `padding` to appear only in the "successful" scenario, try adding it as a "no more items indicator". For example:
```dart
builderDelegate: PagedChildBuilderDelegate<YourItemType>(
    noMoreItemsIndicatorBuilder: (_) => Container(
        height: 90,
    ),
    ...
)
```

**Comment by shilangyu** [comment]
> If you want your `padding` to appear only in the "successful" scenario, try adding it as a "no more items indicator". For example:
> 
> ```dart
> builderDelegate: PagedChildBuilderDelegate<YourItemType>(
>     noMoreItemsIndicatorBuilder: (_) => Container(
>         height: 90,
>     ),
>     ...
> )
> ```

That does not really solve the problem, this can only add a bottom padding.

The goal is to be able to display in the center widgets from `PagedChildBuilderDelegate`, but the padding on the `PagedListView` adds extra scroll.

@rulim34 did you manage to get it working properly?
