### ISSUE TITLE
How to get visible items?

### ISSUE THREAD

**Issue by valerybodak** [EdsonBueno/infinite_scroll_pagination#42]
@EdsonBueno Could you please clarify, how can I get current visible items?

**Comment by EdsonBueno** [comment]
https://pub.dev/documentation/infinite_scroll_pagination/latest/infinite_scroll_pagination/PagingController/itemList.html

**Comment by valerybodak** [comment]
@EdsonBueno But **itemList** is the list with all items loaded so far. My question was about only current **visible** items...

**Comment by EdsonBueno** [comment]
Oh, I'm sorry! There isn't a built in way to do that.

**Comment by GianlucaAntolini** [comment]
> @EdsonBueno But **itemList** is the list with all items loaded so far. My question was about only current **visible** items...

Hi 😀 wondering if anyone got a solution for this, even if not using a built in way??
