### ISSUE TITLE
Prevent content disappearing on refresh()

### ISSUE THREAD

**Issue by alekbarszczewski** [EdsonBueno/infinite_scroll_pagination#45]
On pullToRefresh I would like to leave content in infinite_scroll_pagination "as is" if there are no new items (new items appear on the top as in Instagram for example). I want content to be replaced by refresh only when the initial state changed. My point is that when using pullToRefresh first infinite_scroll_pagination removes all content (all items) leaving blank page with loading indicator and then after items are loaded it displays them again. Looks weird if those are exactly same items. Instead I would like to show loader over current content and replace content only if new items are available. Is there any way to achieve this in infinite_scroll_pagination?

Ideally if there was a method `setPage()` (in addition to `appendPage()` and `appendLastPage()`) which would just set current state of paging controller.

```dart
RefreshIndicator(
  onRefresh: () => Future.sync(
    // () => pagingController.refresh(), <- instead of this
    // do this ->
    () async {
      final result = await getLatestItems();
      if (/* custom logic to check if paging content should be replaced because new items are available */) {
        pagingController.setPage(result.items, result.nextCursor);
      }  
    }
  ),
  child: PagedListView<Cursor, ActivityDocument>(...),
);
```

**Comment by EdsonBueno** [comment]
Hi @alekbarszczewski.
You can use the `value` property of `PagingController`.
For example:
```dart
_pagingController.value = PagingState(
  nextPageKey: result.nextCursor,
  error: null,
  itemList: result.items,
      );
```

Let me know if that helps. I'm closing the issue for now, but feel free to reopen it in case your problem persists.

**Comment by dharambudh1** [comment]
Hi, @EdsonBueno. I am looking for your help.
