### ISSUE TITLE
Is it possible to handle scroll UP to load more?

### ISSUE THREAD

**Issue by valerybodak** [EdsonBueno/infinite_scroll_pagination#46]
I see that we can handle scroll DOWN to load more, but is it possible to handle scroll UP as well to load more? For example, initial page is 2. So when I scroll to top I need to fetch page 1 etc.

**Comment by EdsonBueno** [comment]
Yes, it is!
Set the `reverse` property from `PagedListView` to `true`.
Keep in mind that the "page ordering" is on you. The `PagingController` will ask first whatever page number you provided on its constructor.

**Comment by valerybodak** [comment]
@EdsonBueno 
But looks like we can't enable the pagination to both directions (up & down). For example, if the initial index is 2, I need to scroll down to fetch page 3 etc.  and I need to scroll up to fetch 1, 0.
Can I enable this behaviour?

**Comment by EdsonBueno** [comment]
Ooooh, wow! Now I get it...
No, that's not possible...

**Comment by zefaxet** [comment]
When you say it's not possible, do you mean just as a limitation of this widget?
This other repository:
https://github.com/fluttercommunity/flutter_infinite_listview
accomplishes what @valerybodak is asking for, but it uses the normal index-based generator that the normal `ListView` uses. I would prefer to use the key-based builder pattern implemented on this widget, and it seems to me like a small effort to combine these two features here.

**Comment by EdsonBueno** [comment]
@zefaxet From what I could understand, the package you listed has nothing to do with pagination, it's just a circular `ListView`. When you reach the end of it, you start seeing the initial items again.
Did I got it wrong?

**Comment by zefaxet** [comment]
Not quite. Example:
Let's say you create the exemplar `PagingController` hooked up to the `Article` repository (referencing [your guide here](https://www.raywenderlich.com/14214369-infinite-scrolling-pagination-in-flutter)), but instead you give the controller `firstPageKey: 2`. When you scroll down, you end up dispatching requests for page 3, 4, 5, etc...

What @valerybodak is asking for is, if they were to scroll up in this case, for the controller to dispatch a request for page 1 and prepend it to the top of the scroll view (preserving order).

You're right that the package I linked is not paginating anything, but it is not circular. Is is able to generate indices infinitely in both directions, up or down, allowing you to have infinite scroll in both directions. I think this concept can be extended to your implementation of the `PagingController`. I'm new to Dart so I might have missed some semantics, but I think at a high level all you need to do is add a new key boundary for the controller to keep track of the top of the page results as well as the bottom (what it does now). Then you should be able to invoke something like:

```dart
void prependPage(List<ItemType> newItems, PageKeyType nextReversePageKey) {
  ...
}
```

Can't figure out a better name for `nextReversePageKey` so I hope my explanation clears up what that's supposed to mean.

What do you think?

**Comment by EdsonBueno** [comment]
It can definitely be done, and the API you suggested would work. But, I'm afraid the inner workings of this aren't that simple, not to mention the visual aspects (loading and error indicators).
Another thing we have to keep in mind, is that if this isn't something lots of users need, it would just bloat up the API and make the package more confusing to use.

**Comment by zefaxet** [comment]
I agree with creating a new widget for this. I was going to suggest that next so it's good to see there's room for the feature if the demand comes.

**Comment by sachin052** [comment]
> I agree with creating a new widget for this. I was going to suggest that next so it's good to see there's room for the feature if the demand comes.

It's a great Idea. I'm looking for the same

**Comment by EdsonBueno** [comment]
From now on, let's track this issue [here](https://github.com/EdsonBueno/infinite_scroll_pagination/issues/56).
I think it's better explained over there.

**Comment by IvanAleksandrov94** [comment]
You can try at the moment to use the implementation with Viewport.
```dart
class LoadMoreUpAndDown extends StatefulWidget {
  const LoadMoreUpAndDown({Key? key}) : super(key: key);

  @override
  _LoadMoreUpAndDownState createState() => _LoadMoreUpAndDownState();
}

class _LoadMoreUpAndDownState extends State<LoadMoreUpAndDown> {
  final Key downListKey = UniqueKey();
  static const _pageSize = 20;

  final PagingController<int, Message> _pagingReplyUpController = PagingController(
    firstPageKey: 0,
  );
  final PagingController<int, Message> _pagingReplyDownController = PagingController(
    firstPageKey: 0,
  );

  Future<void> _fetchUpPage(int pageKey) async {
    try {
      final newItems = await RemoteApi.getMessagesList(pageKey, _pageSize);
      final isLastPage = newItems.length < _pageSize;
      if (isLastPage) {
        _pagingReplyUpController.appendLastPage(newItems);
      } else {
        final nextPageKey = pageKey + newItems.length;
        _pagingReplyUpController.appendPage(newItems, nextPageKey);
      }
    } catch (error) {
      _pagingReplyUpController.error = error;
    }
  }

  Future<void> _fetchDownPage(int pageKey) async {
    try {
      final newItems = await RemoteApi.getMessagesList(pageKey, _pageSize);
      final isLastPage = newItems.length < _pageSize;
      if (isLastPage) {
        _pagingReplyDownController.appendLastPage(newItems);
      } else {
        final nextPageKey = pageKey + newItems.length;
        _pagingReplyDownController.appendPage(newItems, nextPageKey);
      }
    } catch (error) {
      _pagingReplyDownController.error = error;
    }
  }

  @override
  void initState() {
    super.initState();
    _pagingReplyUpController.addPageRequestListener((pageKey) {
      _fetchUpPage(pageKey);
    });

    _pagingReplyDownController.addPageRequestListener((pageKey) {
      _fetchDownPage(pageKey);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scrollable(
      viewportBuilder: (BuildContext context, ViewportOffset position) {
        return Viewport(
          offset: position,
          center: downListKey,
          slivers: [
            PagedSliverList(
              pagingController: _pagingReplyUpController,
              builderDelegate: PagedChildBuilderDelegate<Message>(
                itemBuilder: (context, messageUp, index) => SizedBox(
                  height: 50,
                  width: double.infinity,
                  child: Text(
                    '${messageUp.text}',
                  ),
                ),
              ),
            ),
            PagedSliverList(
              key: downListKey,
              pagingController: _pagingReplyDownController,
              builderDelegate: PagedChildBuilderDelegate<Message>(
                itemBuilder: (context, messageDown, index) => SizedBox(
                  height: 50,
                  width: double.infinity,
                  child: Text(
                    '${messageDown.text}',
                  ),
                ),
              ),
            ),
          ],
        );
      },
    );
  }

  @override
  void dispose() {
    _pagingReplyUpController.dispose();
    _pagingReplyDownController.dispose();
    super.dispose();
  }
}
```

**Comment by Amber916Young** [comment]
Is possible to make the first item display in the top and  when reverse set true? for example like a chat app, the first message should display from top to down, and scrolling up to load more. When i set  reverse to true, the first message display at the bottom

**Comment by MohammedShehata** [comment]
@Amber916Young did you figure a solution for this, I have the same issue, when setting the reverse param to true, the list start filling the bottom of the screen instead of filling top then push it down if has more pages.

Any help guys!
