### ISSUE TITLE
[Feature Request] - Sticky Header

### ISSUE THREAD

**Issue by ariefwijaya** [EdsonBueno/infinite_scroll_pagination#48]
I think it would be useful if we can add this feature in the List. 
What do you think ?

**Comment by EdsonBueno** [comment]
Hi @ariefwijaya .
This is outside of the package's scope.
The package provides you `PagedSliverList`, a [Sliver version](https://medium.com/flutter/slivers-demystified-6ff68ab0296f) of a paginated list. That is all you need to create a sticky header on your side.
Thank you so much. Feel free to ping me on [our chat](https://gitter.im/infinite_scroll_pagination/community) in case you still have any doubts.

**Comment by sm2017** [comment]
@EdsonBueno I asked same question in the chat, but it seems the chat is inactive for a month

Do you have any sticky header example? I need to have 2 sticky header in my infinite scroll

1. A side sticky header that stick avatar of the user
2. A top sticky header that date if records

**Comment by EdsonBueno** [comment]
Hi @sm2017 , the chat is by no means inactive. I just answered you there.
Thank you.
