### ISSUE TITLE
[Feature Request] - Add Debounce /Throttle in pagingController.refresh() method

### ISSUE THREAD

**Issue by ariefwijaya** [EdsonBueno/infinite_scroll_pagination#49]
When implement search / filtering. I would be helpful if we can add debounce when calling refresh method. Moreover we call it  in onChanged callback.

**Comment by EdsonBueno** [comment]
Hi @ariefwijaya .
That is outside of the package's scope. You should handle the debouncing yourself.
There are multiple ways for you to do that. The example project, for example (:P), [handles it on the input](https://github.com/EdsonBueno/infinite_scroll_pagination/blob/master/example/lib/presentation/common/character_search_input_sliver.dart).
