### ISSUE TITLE
[Question] return Widgets as a Fake Items in a builder

### ISSUE THREAD

**Issue by ariefwijaya** [EdsonBueno/infinite_scroll_pagination#51]
In the **firstPageProgressIndicatorBuilder** and  **newPageProgressIndicatorBuilder**, we can custom our widget to be shown. But how to show fake items  with those builder ? For Eg. 8 Items for firstPageProgressIndicatorBuilder or 2 Items for newPageProgressIndicatorBuilder. The idea is I want to show the skeleton loader. It might be worked in the Listview but not in GridView.

**Comment by EdsonBueno** [comment]
1. Create a widget that will represent your skeleton items;
2. In your builders, return a `Column` with the desired amount of skeleton widgets as children;
