### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by Fethi1** [EdsonBueno/infinite_scroll_pagination#52]
`infinite_scroll_pagination: ^2.3.0`

The current Flutter SDK version is 1.21.0-6.0.pre.245.
Because app depends on infinite_scroll_pagination >=2.2.0+1which requires Flutter SDK version >=1.22.0 <2.0.0, version solving failed.

**Comment by EdsonBueno** [comment]
You need to upgrade your Flutter SDK version.
Infinite Scroll Pagination needs at least 1.22.
