### ISSUE TITLE
noItemsFoundIndicatorBuilder refresh doesn't work

### ISSUE THREAD

**Issue by Martibis** [EdsonBueno/infinite_scroll_pagination#59]
When no items are found the refresh indicator doesn't function, it makes sense that it does function in this case in my opinion.

**Comment by EdsonBueno** [comment]
Hi @Martibis .
Please, can you provide some code?
I want to know exactly what you mean with refresh indicator.

**Comment by Martibis** [comment]
https://user-images.githubusercontent.com/13279066/109838142-2ed1fa00-7c46-11eb-95cd-6f5e1e51a48b.mp4


Basically there I have two tabs and inside each TabView there is the following. 

```
child: RefreshIndicator(
        color: Theme.of(context).primaryColor,
        onRefresh: () async {
          BlocProvider.of<T>(context).add(FetchPosts(pageKey: 0, type: type));
        },
        child: PagedListView(
            addAutomaticKeepAlives: false,
            scrollController: _scrollController,
            pagingController: _pagingController,
            builderDelegate: PagedChildBuilderDelegate<Post>(
              noItemsFoundIndicatorBuilder: (context) => EmptyListIndicator(),
              noMoreItemsIndicatorBuilder: (context) => NoMoreItemsIndicator(),
              firstPageErrorIndicatorBuilder: (context) => ErrorIndicator(
                error: _pagingController.error,
                onTryAgain: () => _pagingController.refresh(),
              ),
              newPageErrorIndicatorBuilder: (context) => Text('Error'),
              firstPageProgressIndicatorBuilder: (context) => Text('Loading'),
              newPageProgressIndicatorBuilder: (context) => Text('Loading'),
              itemBuilder: (context, item, index) {
                return FeedPost<T>(
                  p: item,
                  type: type,
                  key: UniqueKey(),
                );
              },
            )),
      ),
```

I am able to refresh if the PagedListView has items, but if it doesn't I can't refresh.

**Comment by EdsonBueno** [comment]
It works perfectly on our sample app, weird...
It's probably something with your layout structure. I'm closing the issue for now, but if you're able to give me access to a toy project reproducing the issue I'll be glad to help you!
Ping me on [our chat](https://gitter.im/infinite_scroll_pagination/community) when you have it!

**Comment by Martibis** [comment]
Found the solution, you need to set physics to AlwaysScrollableScrollPhysics() in the PagedListView, found the solution here: https://github.com/flutter/flutter/issues/15197
