### ISSUE TITLE
Customizable text

### ISSUE THREAD

**Issue by josalhor** [EdsonBueno/infinite_scroll_pagination#60]
Hello,

I was recently using `FirstPageExceptionIndicator` and I notice there is no way to customize the `'Try Again'` message. I am from Spain where Spanish, Catalan, and other languages are quite common. Naturally, it would be undesirable to leave an error message in another language. My only way to provide a custom text on the label is to copy-paste the widget and change the text.

Setting aside that I probably shouldn't rely on implementation classes (although the example makes use of them), could the text for the button be customizable?

Edit: I have just found the same issue with `NewPageErrorIndicator`

**Comment by EdsonBueno** [comment]
Hi @josalhor.
The purpose of the package is to deal with pagination and infinite scrolling, not to provide user-facing widgets.
The default indicator widgets are there just for convenience and to avoid breaking the app if the developer doesn't provide any custom indicators.
That all said, the correct solution for you is [provide a widget of your own](https://pub.dev/packages/infinite_scroll_pagination/example#customizing-indicators) for the indicators.
Thank you!
