### ISSUE TITLE
How to set empty list or empty widget when no data from server?

### ISSUE THREAD

**Issue by davemg3** [EdsonBueno/infinite_scroll_pagination#61]
Currently. No data equals firstPageProgressIndicatorBuilder displayed. 
How to get rid of that? What need to be returned to pagingController?
Thanks

**Comment by EdsonBueno** [comment]
You need to append a new page.
I recommend that you go through our [step-by-step tutorial](https://www.raywenderlich.com/14214369-infinite-scrolling-pagination-in-flutter).
