### ISSUE TITLE
PagedListView not working as expected inside CustomScrollView

### ISSUE THREAD

**Issue by Martibis** [EdsonBueno/infinite_scroll_pagination#62]
Current behavior: when scrolling within the PagedListView the SliverAppBar will not collapse / expand. It only collapses / expands when scrolling within the SliverAppBar itself.

Expected behavior: the SliverAppBar expands / collapses correctly when scrolling anywhere on the screen.

If there is no TabBarView I could just add PagedSliverList, but that's not really an option here I think.

```
Scaffold(
        body: CustomScrollView(
      slivers: [
        SliverAppBar(),
        SliverFillRemaining(
          child: Column(
            children: [
              TabBar(
                controller: _controller,
                tabs: [Tab(text: "latest")],
              ),
              Expanded(
                child: TabBarView(
                  controller: _controller,
                  children: [PagedListView],
                ),
              )
            ],
          ),
        ) 
      ],
    ));
```

Current behavior:

https://user-images.githubusercontent.com/13279066/110826675-9bc44000-8295-11eb-8611-e5f4a5ad4668.mp4

Expected behavior:
![1_mmgVUVJbYJpYVG6aeoyrNg](https://user-images.githubusercontent.com/13279066/110831836-ebf1d100-829a-11eb-8f94-99e38586f14b.gif)

**Comment by EdsonBueno** [comment]
Hi @Martibis .
Can you try replacing the `PagedListView` with a regular `ListView` with fake items?
That way we can know for sure if it's something with the package or not.
Thank you

**Comment by Martibis** [comment]
> Hi @Martibis .
> Can you try replacing `PagedListView` with a regular `ListView` with fake items?
> That way we can know for sure if it's something with the package or not.
> Thank you

With a ListView I didn't have the issue, but I figured out why and it's not the package I think (just weird Flutter behavior). When I was using a PagedListView I was using a ScrollController in there so I would be able to scroll back to the top on a button press. Having a Scrollcontroller in there is what was causing this issue!

**Comment by Galti** [comment]
I want to implement similar behavior with ```PagedGridView```.
Flutter automatically provides the behavior if you have ```SliverList``` or ```SliverGrid```  inside ```CustomScrollView```.

Anyone created this behavior?

**Comment by melmarzgioui** [comment]
im experiencing the same problem has anybody a solution

**Comment by Dhanush-Ma** [comment]
https://github.com/EdsonBueno/infinite_scroll_pagination/issues/47#issuecomment-775796276
