### ISSUE TITLE
[Question]Is there a way to turn the PagedList into Sliver?

### ISSUE THREAD

**Issue by SeasonLeee** [EdsonBueno/infinite_scroll_pagination#63]
I want to use PagedList inside a CustomScrollView... I have tried the SliverToBoxAdapter but failed...

The reason why I am doing this "use PagedList inside a CustomScrollView" is because, I need to use structure similar to this example https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html#widgets.NestedScrollView.3

That I will have a SliverAppbar with tabbar at the bottom of the AppBar, and PagedList inside each tab which inside TabBarView...

And I need to use the example above is that I have to make the SliverAppBar reactive to the scrolling gesture of the list, that the AppBar should collapse but keep tabs when the list is scrolling up(I am reading the list items in the bottom, so my gesture is scrolling up), and the AppBar should open or stretch to full when the list is scroll down(I am reading the list items in the top, so my gesture is scrolling down)

So, is there any solution to the question I asked in the title?

Thanks!

**Comment by EdsonBueno** [comment]
Hi @SeasonLeee .
The package has a `PagedSliverList` widget.
Thank you

**Comment by SeasonLeee** [comment]
Yeah, I know that, but the `PagedSliverList` widget is way too complicate to use and no full document on usage of certain api.

Or maybe you could elaborate here on the exact usage of 

what is this `completedListingBuilder` in here about? What's the different between `builderDelegate` and `completedListingBuilder`??? is it really necessary?? (well, I know it's required when it comes to the code, it's mark @required). But I don't know what it means..... completed listing??? I thought after the render complete, we will get what's in the builderDelegate...

```
@override
Widget build(BuildContext context) =>
    PagedSliverBuilder<PageKeyType, ItemType>(
      pagingController: pagingController,
      builderDelegate: builderDelegate,
      completedListingBuilder: (
        context,
        itemBuilder,
        itemCount,
        noMoreItemsIndicatorBuilder,
      ) =>
          SliverGrid(
        gridDelegate: gridDelegate,
        delegate: _buildSliverDelegate(
          itemBuilder,
          itemCount,
          statusIndicatorBuilder: noMoreItemsIndicatorBuilder,
        ),
      ),
      loadingListingBuilder: (
        context,
        itemBuilder,
        itemCount,
        progressIndicatorBuilder,
      ) =>
          SliverGrid(
        gridDelegate: gridDelegate,
        delegate: _buildSliverDelegate(
          itemBuilder,
          itemCount,
          statusIndicatorBuilder: progressIndicatorBuilder,
        ),
      ),
      errorListingBuilder: (
        context,
        itemBuilder,
        itemCount,
        errorIndicatorBuilder,
      ) =>
          SliverGrid(
        gridDelegate: gridDelegate,
        delegate: _buildSliverDelegate(
          itemBuilder,
          itemCount,
          statusIndicatorBuilder: errorIndicatorBuilder,
        ),
      ),
    );
```

Thanks in advance!

**Comment by EdsonBueno** [comment]
You're trying to use PagedSliver**Builder** instead of PagedSliver**List**.
