### ISSUE TITLE
[Example Request] Riverpod state management

### ISSUE THREAD

**Issue by rulim34** [EdsonBueno/infinite_scroll_pagination#65]
Could you add an example of using riverpod with this package please? I'm still a newbie and quite confused.

**Comment by EdsonBueno** [comment]
Hi @rulim34.
Yes, definitely!
I'm just not sure when I'll be able to do it then. So, hang in tight!

**Comment by rulim34** [comment]
Thanks in advance @EdsonBueno, I hope you have free time for that soon.

**Comment by rulim34** [comment]
@EdsonBueno Could you give me a little hint?
`
@override
  void initState() {
    super.initState();
    _pagingController.addPageRequestListener((pageKey) {
      // TODO implement fecth page
    });
  }
`
I'm using StateNotifier with StateNotifierProvider with 4 state (Loading, AppendLast, Append, Error) at the moment. Should I replace it?

**Comment by EdsonBueno** [comment]
Hi @rulim34,
I'm afraid I don't know Riverpod to help you with this yet.
But, from what you wrote, I can suggest you use only one state. Take a look at the BLoC example on our example project, I think it will help you.

**Comment by PhyoLinMg** [comment]
I have written an example of riverpod with infinite_scroll_pagination. If there is someone who wants to review my code. Here is [the link](https://github.com/PhyoLinMg/riverpod_pagination_example)

**Comment by quantosapplications** [comment]
Hi, I have developed a library that I use in my projects.
It is simple and customizable and abstracts away the complexity of using this library with riverpods 😱
This is the link https://pub.dev/packages/riverpod_infinite_scroll

**Comment by chrisgate** [comment]
@quantosapplications is riverpod_infinite_scroll on github? i like to run the example first to use...cheers and nice work.

**Comment by quantosapplications** [comment]
hi @chrisgate yes of course, it's here https://github.com/quantosapplications/riverpod_infinite_scroll
There is an example folder with a simple project that you can run
