### ISSUE TITLE
Question: noItemsFoundIndicatorBuilder with empty data

### ISSUE THREAD

**Issue by spawn81** [EdsonBueno/infinite_scroll_pagination#67]
Hi,
first of all, thanks for this helpful package.
I'm trying to implement the noItemsFoundIndicatorBuilder, i've followed the suggested tutorial, but I cannot make it work.
I get this error "type 'Null' is not a subtype of type 'int' in type cast" that comes (I think ) from the fromJson convertion of my model.

The search api I use return an empy array in case of no match:
`{"data":[],"links":{"first":"http:\/\/192.168.1.5:8000\/api\/search?q=testi&page=1","last":"http:\/\/192.168.1.5:8000\/api\/search?q=testi&page=1","prev":null,"next":null},"meta":{"current_page":1,"from":null,"last_page":1,"path":"http:\/\/192.168.1.5:8000\/api\/search","per_page":15,"to":null,"total":0}}`
This is the fetch fuction for pagination:
```
Future<void> _fetchPage(pageKey) async {
    final newItems;
    try {
      if (_searchTerm != null &&
          _searchTerm!.isNotEmpty &&
          _searchTerm!.length >= 4) {
        newItems =
            await newsApi.searchNewsList(pageKey, searchTerm: _searchTerm);
      } else {
        newItems = await newsApi.getNewsList(
          pageKey,
        );
      }
      final isLastPage = newItems.meta.lastPage == newItems.meta.currentPage;
      if (isLastPage) {
        if (newItems.meta.total != 0)
          _pagingController.appendLastPage(newItems.data);
  
          
      } else {
        final int nextPageKey = newItems.meta.currentPage + 1;
        print(nextPageKey);

        _pagingController.appendPage(newItems.data, nextPageKey);
      }
    } catch (error) {
      _pagingController.error = error;
      print(error);
    }
  }
```
How does the package knows the the data list is empty?
Should I throw an exception for the 404?
Thank you

**Comment by EdsonBueno** [comment]
Hi @spawn81 .
The package knows your page is empty if it has an empty list and a `null` next page key.
You'll need to check your exception's stack trace to find out where the error is happening.
If you still have any doubts, feel free to ping me in [our chat](https://gitter.im/infinite_scroll_pagination/community).
