### ISSUE TITLE
[Question]How to support different type(size or content) of list element?

### ISSUE THREAD

**Issue by SeasonLeee** [EdsonBueno/infinite_scroll_pagination#68]
There's a `CustomScrollView` in Flutter that it accept different kind of widget(sliver) and making them 'List'...

I wonder if this package support feature like that?

Yeah, I know that there's a `PagedSliverList`... but I'm not sure if it's the sam as `SliverList` or can I use it as CustomScrollView...

Thanks!

**Comment by SeasonLeee** [comment]
Or to ask the question in a different way, how to use different kind of widget in the `PagedList`?

Well, my list item won't be all the same kind of widget, one could be a text, the other could be a picture, and the next might be a picture plus text widget... does `PagedList` currently support this?

Thanks!

**Comment by EdsonBueno** [comment]
Hi @SeasonLeee .
First of all, there's no `PagedList`, only `PagedListView` or `PagedSliverList`.
`PagedListView` works exactly as a `ListView`.
`PagedSliverList` works exactly as a `SliverList`, which means it must be wrapped in a `CustomScrollView` (check out the example project).

If you need different widgets for each item in your pages, simply return different widgets inside your `itemBuilder`.

If you still have any doubts, feel free to ping me in [our chat](https://gitter.im/infinite_scroll_pagination/community).
