### ISSUE TITLE
itemList should not be required to be null to render error state

### ISSUE THREAD

**Issue by RobertHeim** [EdsonBueno/infinite_scroll_pagination#69]
The current implementation renders `noItemsFound` even if `error` is set in the `PageStatus` when `itemList` is not null for the first page request. In other words, `itemList` is required to be null to render an error. From my perception it should render the error state always as soon as the `error` field is set.

This are the lines in `PagingState` that should check the `error` field before checking  `_isEmpty`:
```
    if (_isEmpty) {
      return PagingStatus.noItemsFound;
    } else {
      return PagingStatus.firstPageError;
    }
```

**Comment by EdsonBueno** [comment]
Hi @RobertHeim.
I think it's better to handle "all not covered scenarios" as an error.
Is this an impediment for you in any way?

Thank you for opening the issue. I'm closing it for now, but feel free to continue the discussion.

**Comment by RobertHeim** [comment]
Hey @EdsonBueno.
I agree that "not covered" scenarios should be an error, but I meant that **if I set the `error` field, that I would expect an error and not an "no items found"**.

In our case this now looks cumbersome in the error scenario where the first page has a request error:

```
_pagingController.value.value = PagingState(
            nextPageKey: currentPeriodStart,
            error: 'request-failed',
            itemList: state.byPeriod.byPeriodStart.length == 1
                /* important to set the itemList null if the error is on the
                    first page, otherwise the lib will not render the error
                    indicator, but "no items found" => see
                    https://github.com/EdsonBueno/infinite_scroll_pagination/issues/69
                */
                ? null
                : mergeEmptyPeriods(
                    state.byPeriod.byPeriodStart.values.toList()),
          )
```
Out BLoC tracks items by periods (e.g. weeks) and page correlates to a period. The BLoC tracks the requests completely async (i.e. there are events for `Request`, `Success`, `Failure` that emit a corresponding status per period).
