### ISSUE TITLE
Two way infinite scroll

### ISSUE THREAD

**Issue by sm2017** [EdsonBueno/infinite_scroll_pagination#71]
@EdsonBueno Is it possible to have a two way infinite scrolling?
I am creating a chat application, when you click on a room, the infinite scroller fetch messages, When you scroll up infinite scroller fetch more and more messages
When you have unread messages it jump to first unread message once you click on the room, When you have too many unread messages, the unread messages must be fetched page by page, so when you scroll down , infinite scroller must fetch next unread messages

**Comment by EdsonBueno** [comment]
Hi @sm2017,
This is currently not possible, but it's on my roadmap.
We're using [this issue](https://github.com/EdsonBueno/infinite_scroll_pagination/issues/56) to track everyone that wants this feature.
