### ISSUE TITLE
Clear all Items in the PagingController

### ISSUE THREAD

**Issue by Keithwachira** [EdsonBueno/infinite_scroll_pagination#72]
Do we have a method that I can use to clear all items in the PagingController  for example something like.

PagingController.clearAll().

**Comment by EdsonBueno** [comment]
Hi @Keithwachira ,
We have `pagingController.refresh()`.

**Comment by Keithwachira** [comment]
I wanted a way to clear without refetching the data.....with refresh it also refetch the data.....(I.e it sends a http request )

**Comment by EdsonBueno** [comment]
What do you need this for?

**Comment by 0wzZZzz6** [comment]
I also need this. For example. I want to replace with new data.

**Comment by yalda-student** [comment]
Hi. Did you find any solution to clear data?
