### ISSUE TITLE
[Question]How to use the package along with the Provider package?

### ISSUE THREAD

**Issue by SeasonLeee** [EdsonBueno/infinite_scroll_pagination#75]
_I was accidentally click the post button while I as still editing..._

Thanks for the awesome package, but I kind of stuck at converting how the data in the widget retrieve from `List` in `Provider` to the `List` in `PaginationController`...

Any advice?

Thanks...

ps: link to `provider` package: https://pub.dev/packages/provider

**Comment by EdsonBueno** [comment]
Hi @SeasonLeee ,
Here's how I would do it: Make a Provider that emits `PagingState`s. Then, in your widgets, give the `PagingState` to the `value` property of the `PagingController`.

**Comment by SeasonLeee** [comment]
@EdsonBueno ...🤔🤔🤔... 

let me elaborate the issue further... 

So, first, I retrieve the data from the internet and pass it to the data field in `Provider` class, then I render the data using the `Consumer` widget, which will sort of rebuild itself if the data in `Provider` change... 

And now, I want to implement a pagination feature to the list that's already used in the `Provider`...

And the way how `PagedList` work, I believe is that I retrieve the data from the internet and pass it to the `PagingController` using the build in method, `appendPage`, which is how I have done in the place where we don't need the list to be dynamically change due to local data change...

So, if I change how the list get its data from `Provider` to `PagedList`(which is from PagingController), then how can I have the dynamic change nature from `Provider`?

Thank you!

**Comment by EdsonBueno** [comment]
Since now you're managing your state inside your `Provider`, you shouldn't use `appendPage` or `appendLastPage` anymore.
Now, append your items and handle your errors inside your `Provider`, and make your `Provider` expose a `PagingState` instead of just the item list.
Then, create your `PagingController` on `initState`, but update its `value` inside your `Consumer` builder.

**Comment by SeasonLeee** [comment]
Thanks for replying... but I kind of confuse... (probably I'm too inexperience on this....)

What I got from your reply... it seems, the UI is still rendered by the `Consumer`(part of the `provider`, a widget will update its part if the data in the `provider` change)... but if we render UI this way, how can we let `PagingController`'s pagination feature help use pagination?

And I don't really get that `PagingState` part...  should I create a new data class implement `PagingState` or extend `PagingState`? Or just instantiate a `PagingState` in the `Provider` data class field? and use it as how we use field in the class?

Thanks!

**Comment by EdsonBueno** [comment]
1. Inside your `Consumer` builder, do something like this:
```dart
return PagedListView<int, CharacterSummary>(
  pagingController: _pagingController..value = pagingState, // this pagingState is the one emitted by the Provider
  builderDelegate: PagedChildBuilderDelegate<CharacterSummary>(
  itemBuilder: (context, item, index) => CharacterListItem(
    character: item,
  ),
);
```

2. As for the `PagingState`, do whatever you want. The easiest way is to use the `PagingState` from the package, without subclassing or anything.

**Comment by SeasonLeee** [comment]
@EdsonBueno hey... Thanks for the reply last time.

 I hate to ask... but... how exactly is this `PagingState` should be used...

I mean... when should we put the value in?(Since it's final, we can just set the value later...)

And some how I manage to put the value in, but how to update it's status...

Sorry for being so annoying... but the documentation about the `PagingState` is quite limited....

Thank you again!

**Comment by SeasonLeee** [comment]
@EdsonBueno 

Could you give me an example how to update the `PagingState`?

There's no direct way to update its value... I don't understand how it can be use with the value in the `provider`...

![image](https://user-images.githubusercontent.com/13610283/114979914-3c71d500-9ebe-11eb-8fcc-8e8a37291b05.png)

Also we can see from the doc that this class is immutable... then... the nature of the data in `provider` class is dynamic... 

so... how?

Thank you!

**Comment by SeasonLeee** [comment]
> Now, append your items and handle your errors inside your `Provider`, and make your `Provider` expose a `PagingState` instead of just the item list.

When should I append my list in `provider`?

I mean it's there a way to know the list is scrolling to almost the end?

The appending of the new data should happen in scenario like above. 

But the above case is kind of unknown to me...  

In a word, where and when to do the "pagination"?

Thanks!
