### ISSUE TITLE
How could the situation where the controller is refreshed but a previous future that completes after it, causing old data to be inserted to the page, be handled?

### ISSUE THREAD

**Issue by NamanShergill** [EdsonBueno/infinite_scroll_pagination#79]
I'm not sure how to approach this, basically the refresh controller is called after the future being used to fetch data to display is changed, but if a future was ongoing before the controller was refreshed, it'll insert data based on the previous future to the page. 

The only fix I've figured out so far is passing a different key to the widget containing the pagination based on the data to force it to rebuild from scratch, discarding the current paging controller entirely, but this seems a bit hacky and also makes me lose some animations I am trying to implement around the widget on data change.

```
final newItems = await widget.future(pageNumber, widget.pageSize, refresh,
          _pagingController.itemList?.last);
```

The code of the entire widget is in this file, if it matters:
https://github.com/NamanShergill/onehub/blob/master/lib/common/infinite_scroll_wrapper.dart

**Comment by EdsonBueno** [comment]
Hi @NamanShergill .
Check if the solution detailed [in this comment](https://github.com/EdsonBueno/infinite_scroll_pagination/pull/7#issuecomment-712956309) helps you.
I'm closing the issue for now, but feel free to reopen it at any time.

**Comment by NamanShergill** [comment]
> Hi @NamanShergill .
> Check if the solution detailed [in this comment](https://github.com/EdsonBueno/infinite_scroll_pagination/pull/7#issuecomment-712956309) helps you.
> I'm closing the issue for now, but feel free to reopen it at any time.

Hmm, in my case the widget isn't getting disposed, the future is just using different parameters to fetch data from the API. I did try setting a similar "if" case based on the parameters currently in the future but the page just got stuck on loading if that data wasn't added to the list. Any idea why that might be happening? (The future in the parameter of the widget was updated before the controller was refreshed, but the previous future was still in progress when the refresh was done.)

**Comment by NamanShergill** [comment]
Currently I've worked around this issue by forcing the widget to rebuild by giving it a value key based on the parameters, which works around this issue, but feels kinda hacky.

**Comment by EdsonBueno** [comment]
I know your widget isn't getting disposed, but still looks to me that the `_activeCallbackIdentity` approach might help you with this. Did you take a look at it?

**Comment by NamanShergill** [comment]
> I know your widget isn't getting disposed, but still looks to me that the `_activeCallbackIdentity` approach might help you with this. Did you take a look at it?

Yes I did, by changing the variable whenever the refresh function was called, but if the "if" check failed and no pages were appended, the first page got stuck loading and never loaded (seemed like it never called the fetch page function again with the new future if it was still executing with the old future when it was refreshed). I probably messed something up while implementing it the last time, I will give it a go again. Thanks for the advice!
