### ISSUE TITLE
 The getter 'iterator' was called on null.

### ISSUE THREAD

**Issue by heshesh2010** [EdsonBueno/infinite_scroll_pagination#8]
Hi ,

i'm using mvc pattren here is snap of my code :

 final PagingController<int, Restaurant> pagingNearRestaurantsController =
  PagingController(firstPageKey: 0);

  HomeController() {
    pagingNearRestaurantsController.addPageRequestListener((pageKey) {
      //    _con.listenForOrders(pageKey);
      //  orderRepo.fetchPosts(orderRepo.nextUrl);
      _fetchNearRestaurantsPage(pageKey);
    });
}

  Future<void> _fetchNearRestaurantsPage(pageKey) async {

    if(pageKey==0)
      newNearRestaurantsItems = await restaurantRepo.getNearRestaurants(deliveryAddress.value, deliveryAddress.value,null);
    else
      newNearRestaurantsItems = await restaurantRepo.getNearRestaurants(deliveryAddress.value, deliveryAddress.value,restaurantRepo.nextUrl);

    try{
      final isLastPage = newNearRestaurantsItems.length < _pageNearRestaurantsSize;
      if (isLastPage) {
        pagingNearRestaurantsController.appendLastPage(newNearRestaurantsItems);
      } else {
        final nextPageKey = pageKey + newNearRestaurantsItems.length;
        pagingNearRestaurantsController.appendPage(newNearRestaurantsItems, nextPageKey);
      }
    } catch (error) {
      pagingNearRestaurantsController.error = error;
    }
  }

Future<List<Restaurant>> getNearRestaurants(
    Address myLocation, Address areaLocation,uri) async {

  if(uri==null) {
    uri = Helper.getUri('api/restaurants');
    Map<String, dynamic> _queryParams = {};
    SharedPreferences prefs = await SharedPreferences.getInstance();
    Filter filter = Filter.fromJSON(
        json.decode(
            prefs.getString('filter') ?? new Filter("opened").toJson()));

    if (!myLocation.isUnknown() && !areaLocation.isUnknown()) {
      _queryParams['myLon'] = myLocation.longitude.toString();
      _queryParams['myLat'] = myLocation.latitude.toString();
      _queryParams['areaLon'] = areaLocation.longitude.toString();
      _queryParams['areaLat'] = areaLocation.latitude.toString();
    }
    _queryParams['availability'] = filter.availability.toString();
    uri = uri.replace(queryParameters: _queryParams);
    uriFinal=uri;
  }
  else
    uriFinal=uri;

    http.Response response = await http.get(
        uriFinal );
    var responseJson = json.decode(response.body);
    var data = responseJson['data']['data'];

    if (responseJson['data']['next_page_url'] != null) {
      nextUrl = responseJson['data']['next_page_url'];
    }

    return (data as List)
        .map((p) => Restaurant.fromJSON(p))
        .toList();
}

////
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      new List.from (dart:core-patch/array_patch.dart:57:19)
#2      PagingController.notifyStatusListeners (package:infinite_scroll_pagination/src/core/paging_controller.dart:134:28)
#3      PagingController.value= (package:infinite_scroll_pagination/src/core/paging_controller.dart:175:7)
#4      PagingController.error= (package:infinite_scroll_pagination/src/core/paging_controller.dart:59:5)
#5      HomeController._fetchNearRestaurantsPage (package:foodlobby_client_app/src/controllers/home_controller.dart:72:39)
<asynchronous suspension>
#6      new HomeController.<anonymous closure> (package:foodlobby_client_app/src/controllers/home_controller.dart:40:7)
#7      PagingController.notifyPageRequestListeners.<anonymous closure> (package:infinite_scroll_pagination/src/core/paging<…

**Comment by EdsonBueno** [comment]
Hi @heshesh2010.
Your problem is the same one as the one in [this issue](https://github.com/EdsonBueno/infinite_scroll_pagination/pull/7).
Try using the same solution I provided there. If you face any problems implementing it, or if it doesn't work, contact me on [the chat](https://gitter.im/infinite_scroll_pagination/community) and I'll help you.
