### ISSUE TITLE
controll.onRefresh() make controller called twice 

### ISSUE THREAD

**Issue by heshesh2010** [EdsonBueno/infinite_scroll_pagination#80]
Hi , 

I'm using TabBarView when change tab Item i call  _con.pagingFoodsController.refresh(); 

but what i got dubled items cuz the 

 pagingFoodsController.addPageRequestListener((pageKey) {
      fetchFoodsPage(pageKey);
    });

called twice 

Here my code :
                                     Container(
                                     child: FutureBuilder<List<Category>>(
                                      future: _con.getRestaurantFoodsCategories(),
                                        builder: (c, s) {
                                        if (s.hasData) {
                                         List<Tab> tabs = new List<Tab>();

                                      for (int i = 0; i < s.data.length; i++) {
                                        tabs.add(Tab(
                                          child: Text(
                                            s.data[i].name,
                                            style:
                                                TextStyle(color: Colors.black),
                                          ),
                                        ));
                                      }
                                      TabController tabController =
                                          new TabController(
                                              vsync: this, length: tabs.length);
                                      tabController.addListener(() {
                                        if (tabController.indexIsChanging) {
                                          _con.idOfCategory =
                                              s.data[tabController.index].id;
                                          _con.pagingFoodsController.refresh();
                                          print(s.data[tabController.index].id);

                                          print(
                                              "tab is animating. from active (getting the index) to inactive(getting the index) ");
                                        } else {
                                          //tab is finished animating you get the current index
                                          //here you can get your index or run some method once.
                                          //  print(tabController.index);
                                        }
                                      });
                                      return Container(
                                        height: 500,
                                        child: new MaterialApp(
                                          debugShowCheckedModeBanner: false,
                                          home: new Scaffold(
                                              appBar: new AppBar(
                                                backgroundColor: Theme.of(
                                                        context)
                                                    .scaffoldBackgroundColor,
                                                title: Padding(
                                                  padding: const EdgeInsets
                                                          .symmetric(
                                                      horizontal: 20),
                                                  child: ListTile(
                                                    dense: true,
                                                    contentPadding:
                                                        EdgeInsets.symmetric(
                                                            vertical: 0),
                                                    leading: Icon(
                                                      Icons.restaurant,
                                                      color: Theme.of(context)
                                                          .hintColor,
                                                    ),
                                                    title: Text(
                                                      S
                                                          .of(context)
                                                          .food_categories,
                                                      style: Theme.of(context)
                                                          .textTheme
                                                          .display1,
                                                    ),
                                                  ),
                                                ),
                                                bottom: new TabBar(
                                                  controller: tabController,
                                                  labelColor: Colors.black,
                                                  isScrollable: true,
                                                  tabs: List<Widget>.generate(
                                                      s.data.length,
                                                      (int index) {
                                                    return Tab(
                                                        text:
                                                            s.data[index].name);
                                                  }),
                                                ),
                                              ),
                                              body: new TabBarView(
                                                controller: tabController,
                                                children: List<Widget>.generate(
                                                    s.data.length, (int index) {
                                                  return PagedListView<int,
                                                      Food>.separated(
                                                    scrollDirection:
                                                        Axis.vertical,
                                                    primary: false,
                                                    shrinkWrap: false,
                                                    pagingController: _con
                                                        .pagingFoodsController,
                                                    builderDelegate:
                                                        PagedChildBuilderDelegate<
                                                            Food>(
                                                      itemBuilder: (context,
                                                          item, index) {
                                                        return FoodItemWidget(
                                                          food: item,
                                                          heroTag:
                                                              "menu_food_list",
                                                        );
                                                      },
                                                      noMoreItemsIndicatorBuilder:
                                                          (_) => Padding(
                                                        padding:
                                                            const EdgeInsets
                                                                .all(8.0),
                                                        child: ClipRRect(
                                                          borderRadius:
                                                              BorderRadius
                                                                  .circular(80),
                                                          child: RaisedButton(
                                                            disabledColor:
                                                                Colors.white,
                                                            onPressed: null,
                                                            child: Text(
                                                                "لا يوجد وجبات اخرى"),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                    separatorBuilder: (context,
                                                            index) =>
                                                        SizedBox(height: 10),
                                                  );
                                                }),
                                              )),
                                        ),
                                      );
                                    }
                                    if (s.hasError) print(s.error.toString());
                                    return Center(
                                        child: Text(s.hasError
                                            ? s.error.toString()
                                            : "Loading..."));
                                  },
                                ),
                              ),

MVC controller class : 

            pagingFoodsController.addPageRequestListener((pageKey) {
      //    _con.listenForOrders(pageKey);
      //  orderRepo.fetchPosts(orderRepo.nextUrl);
      fetchFoodsPage(pageKey);
    });

  Future<void> fetchFoodsPage(pageKey) async {
    print("test"); // here is called twice !!!
    if (newFoodsItems.isNotEmpty) {
      if (newFoodsItems.first.category.id != idOfCategory) {
        newFoodsItems.clear();
        if (pageKey == 0)
          newFoodsItems = await foodRepo.getFoodsOfRestaurant(
              idRestaurant, null, idOfCategory);
        else
          newFoodsItems = await foodRepo.getFoodsOfRestaurant(
              idRestaurant, foodRepo.nextUrlTFoodsOfRestaurant, idOfCategory);
      }
    } else {
      if (pageKey == 0)
        newFoodsItems = await foodRepo.getFoodsOfRestaurant(
            idRestaurant, null, idOfCategory);
      else
        newFoodsItems = await foodRepo.getFoodsOfRestaurant(
            idRestaurant, foodRepo.nextUrlTFoodsOfRestaurant, idOfCategory);
    }
    try {
      final isLastPage = newFoodsItems.length < _pageFoodsSize;
      if (isLastPage) {
        pagingFoodsController.appendLastPage(newFoodsItems);
      } else {
        final nextPageKey = pageKey + newFoodsItems.length;
        pagingFoodsController.appendPage(newFoodsItems, nextPageKey);
      }
    } catch (error) {
      pagingFoodsController.error = error;
    }
  }

**Comment by EdsonBueno** [comment]
Hi @heshesh2010 .
It's pretty hard to understand your code because of the formatting.
I'll need a sample app that I can run reproducing the issue.

**Comment by heshesh2010** [comment]
https://share.getcloudapp.com/Jru4nZQ7
https://share.getcloudapp.com/yAuD0e5o
here is my videos shows my app problem
i hope this clear to u

**Comment by EdsonBueno** [comment]
@heshesh2010 I'll need access to your code in order to debug it and help you find the problem.

**Comment by heshesh2010** [comment]
@EdsonBueno I have added you to my project called : tvadl_client
 when you run the app u should hit to any restaurant image to enter the details.dart page so you will find the issue there .

https://share.getcloudapp.com/z8u6mzZ7

thank u for your time

**Comment by EdsonBueno** [comment]
Hi @heshesh2010 .
Your controller is receiving two requests because you have two identical `PagedListView`s using the same controller, one below the other.
![Screen Shot 2021-05-03 at 07 21 52](https://user-images.githubusercontent.com/11272447/116865641-60ccf180-abe0-11eb-9e6c-77c990a0f8e5.png)

**Comment by heshesh2010** [comment]
> Hi @heshesh2010 .
> Your controller is receiving two requests because you have two identical `PagedListView`s using the same controller, one below the other.
> ![Screen Shot 2021-05-03 at 07 21 52](https://user-images.githubusercontent.com/11272447/116865641-60ccf180-abe0-11eb-9e6c-77c990a0f8e5.png)

Hi @EdsonBueno , 

yes I know , i'm using tabview bar , so how to change items with same foodController but with it's different data dynamically , 

i pass category id to my foodController fetch method then i call foodController.refresh() to get new data from api

**Comment by nicks258** [comment]
Did you manage to solve this?
