### ISSUE TITLE
[Feature Request] - Refresh List of Data without change pagination

### ISSUE THREAD

**Issue by ariefwijaya** [EdsonBueno/infinite_scroll_pagination#83]
Currently, when we call refresh() , it will clear all data and get the data from the beginning. Is there any way to refresh the data without change index of pagination ? 
For eg. when we update the data, it will stay on current page with updated data.

**Comment by EdsonBueno** [comment]
hI @ariefwijaya .
Yes, simply change your `PagingController`'s `itemList` and it will update the screen immediately:
```dart
_pagingController. itemList = newItemList;
```

**Comment by EdsonBueno** [comment]
Yes, Flutter will take care of the diff.
