### ISSUE TITLE
[Feature Request] Allow state transition to be animated

### ISSUE THREAD

**Issue by basketball-ico** [EdsonBueno/infinite_scroll_pagination#85]
I would like to make a change more smooth, or animated, for example between `firstProgressIndicatorBuilder` to `itemBuilder`, I do not know if it is currently possible.

for example I think an AnimatedSwitcher would do the job.

https://github.com/EdsonBueno/infinite_scroll_pagination/blob/master/lib/src/ui/paged_sliver_builder.dart#L164-L208

**Comment by EdsonBueno** [comment]
Hi @basketball-ico.
That's not possible currently, but I liked your idea.
Maybe we can let developers choose with a parameter whether they want it animated or not.
I'll edit the issue title in order to make it a feature request.

**Comment by adminVRD** [comment]
Would also love to see this.

**Comment by EdsonBueno** [comment]
This is now available in the 3.1.0 release.
Thank you!
