### ISSUE TITLE
last page not calling correctly 

### ISSUE THREAD

**Issue by heshesh2010** [EdsonBueno/infinite_scroll_pagination#86]
Hi ,

here is my code sample :

  static const _pageFoodsSize = 15;

  Future<void> _fetchFoodsPage(pageKey) async {

    if(pageKey==0&&newFoodsItems.isEmpty)
      newFoodsItems = await foodRepo.getFoodsOfRestaurant(idRestaurant,null);
    else if(pageKey!=0)
      newFoodsItems = await foodRepo.getFoodsOfRestaurant(idRestaurant,foodRepo.nextUrlTFoodsOfRestaurant);

    try{
      final isLastPage = newFoodsItems.length < _pageFoodsSize;
      if (isLastPage) {
        pagingFoodsController.appendLastPage(newFoodsItems);
      } else {
        final nextPageKey = pageKey + newFoodsItems.length;
        pagingFoodsController.appendPage(newFoodsItems, nextPageKey);
      }
    } catch (error) {
      pagingFoodsController.error = error;
    }
  }

my problem is laravel pagination has 15 item's on every page : http://salalorder.com.sa/api/foods?restaurant_id=30

so i got inifinity scrolling and last page (3) is calling many times cuz newFoodsItems.length < _pageFoodsSize is always false 
and isLastPage is always false , so how to check if last page or not

**Comment by EdsonBueno** [comment]
Your API should return either an error or an empty list if you ask for an nonexistent page. Then, you can use that information to set your isLastPage.
