### ISSUE TITLE
how to use tabbar view with same controller using controller.refresh() method

### ISSUE THREAD

**Issue by heshesh2010** [EdsonBueno/infinite_scroll_pagination#87]
Hi ,

do you have any example shows how to use same controller with different items from api that should showing in every tab bar view ?

so when i hit on first tabbar it should get controller items from api that have category = 1 so i call  controller.refresh() to show this new data from api

**Comment by EdsonBueno** [comment]
No, I don't have any examples.
What you're doing doesn't seem correct. You should either use other widget to filter your categories or use one controller per tab.
