### ISSUE TITLE
Multiples Request using Tab

### ISSUE THREAD

**Issue by rajada1** [EdsonBueno/infinite_scroll_pagination#88]
I'm using the tabs
in my initState and call the same widget in the tabView
I change only the items that will be presented, my initState looks like this.

`  void initState() {
    if (widget.typeExpenses == 'send' && !controller.initSend) {
      controller.pagingController.addPageRequestListener((pageKey) {
        controller.fetchPage(
          initStatus: ['send'],
          currentPage: pageKey,
        );
      });
    }
    if (widget.typeExpenses == 'approved') {
      controller.pagingController.addPageRequestListener((pageKey) {
        controller.fetchPage(
          initStatus: ['approved'],
          currentPage: pageKey,
        );
      });
    }
    if (widget.typeExpenses == 'all') {
      controller.pagingController.addPageRequestListener((pageKey) {
        controller.fetchPage(
          currentPage: pageKey,
        );
      });
    }
    super.initState();
  }`
![initState Pagination](https://user-images.githubusercontent.com/39280362/117450331-76f7ec00-af17-11eb-9ea3-2036bb90db1a.png)

If I'm on the second tab, make the second request and go back to the first tab, and make any requests, he will call my fetchPage twice

![interceptonsDioPagination](https://user-images.githubusercontent.com/39280362/117450604-d3f3a200-af17-11eb-80f1-3921c49e2f2b.png)

**Comment by EdsonBueno** [comment]
Hi @rajada1 .
Can you provide me a minimal sample project reproducing the issue?

**Comment by EdsonBueno** [comment]
Hi @rajada1 .
The problem is your `TabPage`s are recreated every time you switch tabs, and consequently, each time you recreate one of them you add another page request listener to your `PagingController`.
There are two options to solve this:
1. Do [this](https://github.com/EdsonBueno/infinite_scroll_pagination/issues/31).
2. Do this:
```dart
@override
void initState() {
  controller.pagingController.addPageRequestListener(controller.fetchPage);
  super.initState();
}

@override
void dispose() {
  controller.pagingController.removePageRequestListener(controller.fetchPage);
  super.dispose();
}
```

**Comment by rajada1** [comment]
sorry i forgot a details.
It doesn't work if I need to add one more argument to the fetchPage method


![code](https://user-images.githubusercontent.com/39280362/118658623-f19bf380-b7c2-11eb-97ee-bd825955d7b6.png)


I updated the repository
