### ISSUE TITLE
Has listeners returns true when none have been attached 

### ISSUE THREAD

**Issue by martipello** [EdsonBueno/infinite_scroll_pagination#91]
Has listeners returns true when none have been attached 

bookingPagingAdapter.pagingController().hasListeners

I'm guessing this is actually because there are internal listeners so maybe this is actually a feature request to have a hasListeners field for user* registered listener

**Comment by EdsonBueno** [comment]
Hi @martipello .
Your diagnosis is correct, it returns `true` because of internal listeners.
I'm curious. What do you need this for?

**Comment by martipello** [comment]
Tbh it was part of my diagnosing the last issue that we closed so it's not needed now, at the time I thought I was registering more than one listener so I wanted to check if a listener was registered and not attach a new one if it already had one, since your comments on the last issue (which the work around is fine btw thank you) I guess this isn't critical maybe you can make it private to remove the ambiguity
