### ISSUE TITLE
Update single item

### ISSUE THREAD

**Issue by jefrisingh** [EdsonBueno/infinite_scroll_pagination#94]
How to update single item inside the list?,
i.e, my list has like button, on click on it need to call api and the result model needs to be updated on the same location, 
Please help me , 
Thanks.

**Comment by EdsonBueno** [comment]
Hi @jefrisingh,
There's no difference between updating a single item or updating all items. Simply assign the updated list to the '_pagingController.itemList' property.

Thank you

**Comment by jefrisingh** [comment]
Thanks @EdsonBueno :+1:

**Comment by ChiPhanTlm** [comment]
I'm not seeing the data in the new item update chagne
