### ISSUE TITLE
Adding item to top of the list

### ISSUE THREAD

**Issue by jefrisingh** [EdsonBueno/infinite_scroll_pagination#95]
Hi, I do have a notes list app, with the pagination api everything is working fine, I have a issue with adding new note on top of the list, after adding the notes the api will return a note, but I can't able to add it in the controller , I need to add it in 0 position, Can any one help me please.

**Comment by jefrisingh** [comment]
complex to use it with getx package

```
if (null != note && null != note.id) {
      final holdOn = pagingController.value;
      holdOn.itemList.insert(0, note);
      pagingController.value = holdOn;
    }
```

I have to use like to the Obx of getx called, Is this the correct way?

**Comment by jefrisingh** [comment]
manually called refresh on Rx to take effect on Obx of getx package, 

```
Note note = await noteRepository.postNote(formData);
    if (null != note && null != note.id) {
      pagingController.value.itemList.insert(0, note);
      pagingController.refresh();
    }
```

It's working for me , is anyone having better solution, please comment it here,
Thanks :)

**Comment by EdsonBueno** [comment]
Hi @jefrisingh .
I believe something like this would work:
'''dart
final previousList = pagingController.itemList;
final newList = [note, ...previousList];
pagingController.itemList = newList;
'''

No refresh needed.
