### ISSUE TITLE
[Feature request] Ability to surface custom error message widgets

### ISSUE THREAD

**Issue by kenthinson** [EdsonBueno/infinite_scroll_pagination#96]
Right now the widget shows a generic message "Something went wrong" "The Application has encountered and unknown error"

It would be nice to be able to pass in a builder that will get called on an error, the builder would then build the UI for the error message. 

For example I might want to surface a message like, your session timed out please log in again. or your network connection is offline, please check your connection and try again. ect.

**Comment by EdsonBueno** [comment]
Hi @kenthinson ,
You can't change **only** the error message, but you can change the whole error widget instead.
https://pub.dev/packages/infinite_scroll_pagination/example#customizing-indicators

**Comment by kenthinson** [comment]
@EdsonBueno  Ah thanks! I totally missed it. Tired brain. Thanks again :)
