### ISSUE TITLE
Keep scrolled position on back from pushed screen

### ISSUE THREAD

**Issue by jefrisingh** [EdsonBueno/infinite_scroll_pagination#97]
Hi , I do have a list of notes , for example 200 with page size of 20 , I scrolled all the way to 121st item and opened it for editing , Then I pressed the back button, now the list in it's 1st position but all pages all loaded (I mean to say not reloaded) , How can I keep the scrolled position? , is there any way to scroll to position like scrolling to 121st item on back?

**Comment by EdsonBueno** [comment]
Hi @jefrisingh ,
The scroll position should be kept by default, but since it's not in your case (probably due to some particularity in your app) try working with `PageStorageKey` from Flutter.
If it doesn't work, I'll need access to a minimal project reproducing the issue.
Thank you so much

**Comment by jefrisingh** [comment]
Sure, I'll try it
